language: c

compiler:
  - gcc

before_script:
  - ./configure

script: make

# whitelist
branches:
  only:
    - travis-ci

notifications:
  email:
    recipients:
      - estetus@gmail.com
    on_success: change
    on_failure: always
