language: c

compiler:
  - gcc

install:
  - sudo apt-get install bash make

script:
  - "bash ./configure"

script: 
  - gmake

# whitelist
branches:
  only:
    - travis-ci

notifications:
  email:
    recipients:
      - estetus@gmail.com
    on_success: change
    on_failure: always
