#!/bin/bash
#

echo "/* This file is auto-generated by configure.sh */" > config.h

echo "[*] Checking system headers."
echo -n "[*] Checking pppox.. "

TMP="/tmp/test-$$"

rm -f "$TMP" || exit 1

cat >>"$TMP.c" << EOF
#include <stdio.h>
#include <netinet/in.h>
#include <linux/if.h>
#include <linux/if_pppox.h>

void main()
{
	struct sockaddr_pppox *pppox;
	printf("%d\n", pppox->sa_addr.pptp.call_id);
}
EOF

gcc "$TMP.c" -o "$TMP" &>"$TMP.log"

if [ ! -x "$TMP" ]; then
	echo "[FAIL]"
else
	echo "[OK]"
	echo "#define USE_PPPOX_PPTP 1" >> config.h
fi

echo

rm -f "$TMP" "$TMP.log" "$TMP.c"

exit 0
