#ifndef _CONSTANTS_H
#define _CONSTANTS_H 1

#define MAX_NR_CHILDREN 64

#define MAX_PIPE_FDS 10

#define MAX_FDS 750

#define REGENERATION_POINT 25000

#define TYPE_MAX 10
#define PROTO_MAX 256

#define DEFAULT_SYSCALLS_PER_CHILD 1000

#define NR_PATHNAMES 50

#endif	/* _CONSTANTS_H */
