#include <dlfcn.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>	// umask
#include <ucontext.h>	// ucontext_t / REG_RIP &c for fault_beacon IP/SP capture
#include <unistd.h>
#if defined(USE_BACKTRACE) && !defined(__SANITIZE_ADDRESS__)
#include <execinfo.h>
#endif

#include "trinity.h"	// __unused__
#include "signals.h"
#include "shm.h"
#include "pids.h"
#include "child.h"

volatile sig_atomic_t sigalrm_pending;
volatile sig_atomic_t xcpu_pending;
volatile sig_atomic_t ctrlc_pending;

/*
 * Cached pointer to glibc's __abort_msg.  Resolved once at child init
 * so there is no link-time GLIBC_PRIVATE dependency: a glibc upgrade
 * that drops the symbol leaves this NULL and the SIGABRT handler
 * silently skips the capture.  This mirrors gdb's pattern for reading
 * the same symbol.  Neither dlvsym() nor dlsym() is async-signal-safe;
 * both are called only from init_abort_msg_capture() below.
 *
 * __abort_msg points at a glibc-internal struct whose layout has been
 * stable since 2.34: a 4-byte size field followed by a NUL-terminated
 * message in a flexible array.  The struct is mirrored locally rather
 * than pulled from a private glibc header.
 */
static struct abort_msg_s {
	unsigned int size;
	char msg[];
} **glibc_abort_msg_p;

void init_abort_msg_capture(void)
{
	/*
	 * Most distros export __abort_msg only under @GLIBC_PRIVATE
	 * with no default-version alias, so a bare dlsym() returns
	 * NULL.  Bind the private version explicitly via dlvsym(), and
	 * fall back to dlsym() for libcs that do expose an unversioned
	 * alias.
	 */
	glibc_abort_msg_p = dlvsym(RTLD_DEFAULT, "__abort_msg", "GLIBC_PRIVATE");
	if (glibc_abort_msg_p == NULL)
		glibc_abort_msg_p = dlsym(RTLD_DEFAULT, "__abort_msg");
}

/*
 * Set while a child is inside do_syscall().  Lets the child fault
 * handler distinguish a SIGSEGV/SIGBUS/SIGILL the child fuzzed at
 * itself via kill(getpid(), SIGFOO) / tkill / tgkill /
 * rt_sigqueueinfo (SI_USER, si_pid == own pid, flag set) from a
 * real fault that just happened to fire at a moment when the child
 * was somewhere else (flag clear -- treat as a real bug, log it).
 */
volatile sig_atomic_t in_do_syscall;

/*
 * SA_SIGINFO version: only honor SIGINT generated by the kernel
 * (si_code > 0, e.g. SI_KERNEL from a terminal ctrl-c).  Any
 * userspace-sent SIGINT — including self-sent via raise()/
 * kill(getpid(), SIGINT)/tgkill(self, SIGINT) — is ignored.
 *
 * Trinity has no internal raise(SIGINT) callers, so a self-sent
 * SIGINT can only come from a child fuzzing the signal-delivery
 * syscalls and happening to pick signal 2 with its own pid as the
 * target.  Honoring those was causing spurious whole-run shutdowns:
 * the child would set ctrlc_pending, then panic(EXIT_SIGINT) on the
 * next loop iteration, the parent saw exit_reason flip, and ~77
 * fuzzing children got reaped for no real reason.
 *
 * Used by both parent and children.  The parent calls panic() directly;
 * children set ctrlc_pending and let the main loop exit cleanly.
 */
static void sigint_handler(__unused__ int sig, siginfo_t *info, __unused__ void *ctx)
{
	/* Only honor real terminal-generated SIGINT (si_code > 0).
	 * SI_USER (0) and below indicate userspace-sent — ignore as
	 * spoofable. */
	if (info->si_code > 0) {
		if (mypid() == mainpid)
			panic(EXIT_SIGINT);
		else
			ctrlc_pending = 1;
	}
}

static __attribute__((no_sanitize("address")))
void sighandler(int sig)
{
	/* Restore default disposition and re-raise so the kernel emits
	 * the usual crash artefacts (signal exit, dmesg log, core if
	 * enabled).  Silent _exit(SUCCESS) hid real fuzzer finds because
	 * the parent saw WIFEXITED(0) instead of WIFSIGNALED(sig). */
	(void)signal(sig, SIG_DFL);
	raise(sig);
}

/*
 * Async-signal-safe formatting primitives for the siginfo dump below.
 * snprintf() is NOT in POSIX 2024 §2.4.3's signal-safe set: glibc's
 * conversion path can touch locale state under an internal lock, and
 * %p/%d are not exempted -- the lock is on the format machinery, not
 * on the conversion specifier.  A fault handler that fires while the
 * thread already holds that lock from a non-handler call would
 * deadlock.  These helpers use only byte stores into a caller-owned
 * stack buffer; no allocation, no globals, no FILE state.
 */
struct sigsafe_buf {
	char *p;
	size_t left;
};

static void sigsafe_putc(struct sigsafe_buf *b, char c)
{
	if (b->left > 0) {
		*b->p++ = c;
		b->left--;
	}
}

static void sigsafe_puts(struct sigsafe_buf *b, const char *s)
{
	while (*s != '\0')
		sigsafe_putc(b, *s++);
}

static void sigsafe_putu(struct sigsafe_buf *b, unsigned long v)
{
	char tmp[24];	/* 20 digits for u64 + slack */
	int i = 0;

	do {
		tmp[i++] = (char)('0' + (v % 10U));
		v /= 10U;
	} while (v != 0);
	while (i-- > 0)
		sigsafe_putc(b, tmp[i]);
}

static void sigsafe_puti(struct sigsafe_buf *b, long v)
{
	unsigned long u;

	if (v < 0) {
		sigsafe_putc(b, '-');
		/* Two-step negate so LONG_MIN does not overflow. */
		u = (unsigned long)(-(v + 1)) + 1UL;
	} else {
		u = (unsigned long)v;
	}
	sigsafe_putu(b, u);
}

static void sigsafe_putp(struct sigsafe_buf *b, const void *p)
{
	static const char hex[] = "0123456789abcdef";
	uintptr_t v = (uintptr_t)p;
	char tmp[2 * sizeof(uintptr_t)];
	int i = 0;

	sigsafe_putc(b, '0');
	sigsafe_putc(b, 'x');
	if (v == 0) {
		sigsafe_putc(b, '0');
		return;
	}
	while (v != 0) {
		tmp[i++] = hex[v & 0xfU];
		v >>= 4;
	}
	while (i-- > 0)
		sigsafe_putc(b, tmp[i]);
}

/*
 * Signal-safe siginfo dump shared by child_fault_handler and
 * main_fault_handler.
 *
 * Don't use psiginfo() -- it calls fmemopen(), which calls calloc(),
 * which deadlocks if this signal was raised by glibc's own abort()
 * while malloc's arena lock is still held by us.  Same family as the
 * libgcc_s/backtrace deadlock fixed in 81143aaeaba6, just one frame up.
 *
 * Hand-roll a signal-safe equivalent: a lookup table covering every
 * signal either fault handler is installed for, formatting via the
 * sigsafe_* helpers above (byte stores into a stack buffer), and a
 * single write().  No allocator involvement, no stdio, no syslog.
 *
 * Used by both the child fault handler (SIGSEGV/SIGABRT/SIGBUS/SIGILL)
 * and the parent's main_fault_handler (which adds SIGFPE/SIGQUIT/
 * SIGTRAP/SIGSYS -- see setup_main_signals).  Without this in the
 * parent path, a SIGSEGV or SIGABRT raised by glibc with the arena
 * lock held (e.g. heap corruption from shm scribble, or an internal
 * assertion) would fmemopen->calloc and wedge the parent's death
 * path forever -- the fleet would then sit on a non-responsive
 * trinity main until something external SIGKILLed it.
 */
static void write_siginfo_safely(int sig, const siginfo_t *info, const char *who)
{
	static const struct {
		int sig;
		const char *name;
	} sigtab[] = {
		{ SIGSEGV, "SIGSEGV" },
		{ SIGABRT, "SIGABRT" },
		{ SIGBUS,  "SIGBUS"  },
		{ SIGILL,  "SIGILL"  },
		{ SIGFPE,  "SIGFPE"  },
		{ SIGQUIT, "SIGQUIT" },
		{ SIGTRAP, "SIGTRAP" },
		{ SIGSYS,  "SIGSYS"  },
	};
	const char *signame = "UNKNOWN";
	char buf[256];
	struct sigsafe_buf b = { buf, sizeof(buf) };
	size_t written;
	ssize_t w;
	size_t i;

	for (i = 0; i < sizeof(sigtab) / sizeof(sigtab[0]); i++) {
		if (sigtab[i].sig == sig) {
			signame = sigtab[i].name;
			break;
		}
	}

	sigsafe_puts(&b, who);
	sigsafe_puts(&b, ": fatal signal: ");
	sigsafe_puts(&b, signame);
	sigsafe_puts(&b, " (si_code=");
	sigsafe_puti(&b, (long)info->si_code);
	sigsafe_puts(&b, ", si_addr=");
	sigsafe_putp(&b, info->si_addr);
	sigsafe_puts(&b, ", si_pid=");
	sigsafe_puti(&b, (long)info->si_pid);
	sigsafe_puts(&b, ")\n");

	written = sizeof(buf) - b.left;
	w = write(STDERR_FILENO, buf, written);
	(void)w;	/* dying anyway; can't act on a short write */
}

/*
 * Async-signal-safe extraction of the faulting PC / SP from the
 * ucontext_t the kernel hands to a SA_SIGINFO handler.  Pure inline
 * reads from caller-owned memory -- no libc, no allocator, no lock.
 *
 * Arches without an inline extractor fall through to NULL, which the
 * beacon consumer treats as "not captured on this build" and prints
 * an explicit placeholder; the rest of the beacon (sig / si_code /
 * si_addr / op_nr / last_syscall_nr) still surfaces.
 */
static void *fault_beacon_extract_ip(const void *ctx)
{
	const ucontext_t *uc = ctx;

	if (uc == NULL)
		return NULL;
#if defined(__x86_64__)
	return (void *)uc->uc_mcontext.gregs[REG_RIP];
#elif defined(__i386__)
	return (void *)uc->uc_mcontext.gregs[REG_EIP];
#elif defined(__aarch64__)
	return (void *)uc->uc_mcontext.pc;
#else
	(void)uc;
	return NULL;
#endif
}

static void *fault_beacon_extract_sp(const void *ctx)
{
	const ucontext_t *uc = ctx;

	if (uc == NULL)
		return NULL;
#if defined(__x86_64__)
	return (void *)uc->uc_mcontext.gregs[REG_RSP];
#elif defined(__i386__)
	return (void *)uc->uc_mcontext.gregs[REG_ESP];
#elif defined(__aarch64__)
	return (void *)uc->uc_mcontext.sp;
#else
	(void)uc;
	return NULL;
#endif
}

/*
 * Child-side fault handler.  Mirrors main_fault_handler in spirit but
 * preserves the existing non-debug clean-exit behaviour:
 *
 *   - Real fault (kernel-generated, si_code > 0) or self-sent (abort,
 *     stack-smash from libc):
 *       * stamp child->fault_beacon BEFORE any libc-touching call so
 *         the parent can surface the death class even when the
 *         backtrace_symbols_fd / open / dup2 chain below re-faults
 *         walking a corrupted ld.so writable segment (see
 *         include/bug_backtrace.h::child_fault_beacon)
 *       * dump backtrace + signal info to stderr so we have ANY signal
 *         in the log even when the core is unwindable (fault from
 *         stack-corruption disturbs the unwind chain — gdb on the
 *         core often gets nothing)
 *       * in debug mode: signal(SIG_DFL) + raise(sig) so the kernel
 *         dumps a core (RLIMIT_CORE was bumped to unlimited in
 *         child.c::disable_coredumps for -D)
 *       * in non-debug: _exit(EXIT_SUCCESS) — matches the legacy
 *         sighandler so the parent's reaper sees a normal exit and
 *         respawns without crash-loop noise
 *
 *   - Sibling-spoofed (process-sent, kill/tkill/tgkill/rt_sigqueueinfo
 *     fuzzing aimed at us): ignore — fuzzer noise.
 */
static __attribute__((no_sanitize("address")))
void child_fault_handler(int sig, siginfo_t *info, void *ctx)
{
	if (info->si_code <= 0 && info->si_pid != mypid()) {
		/* Sibling spoof — ignore. */
		return;
	}
	/*
	 * Self-fuzzed delivery: a child running random_syscall picked
	 * kill / tkill / tgkill / rt_sigqueueinfo / pidfd_send_signal
	 * with target == own pid and signo ∈ {SIGSEGV, SIGBUS, SIGILL,
	 * SIGABRT}.  The kernel obediently delivers it and we land here
	 * with si_code == SI_USER (0) / SI_TKILL (-6) / SI_QUEUE (-1)
	 * and si_pid == getpid().  Drop silently — same _exit path the
	 * non-debug real-fault arm uses below — so the parent's reaper
	 * sees a normal exit and respawns without /tmp/trinity-bug-<pid>.log
	 * polluting the run with fuzzer-generated noise.  Without this
	 * gate, ~25-50% of bug logs in a typical run are own-pid
	 * SIGBUS/SIGILL/SIGSEGV from this exact path.
	 *
	 * Skipped if we're not currently inside do_syscall() — a
	 * self-sent fatal from outside the syscall hot path (e.g. glibc
	 * abort() from a heap-corruption assertion, or an explicit
	 * raise() from trinity itself) is a real bug that must still be
	 * logged.
	 */
	if (info->si_code <= 0 && info->si_pid == mypid() && in_do_syscall) {
		_exit(EXIT_SUCCESS);
	}
	/*
	 * Stamp the fault beacon FIRST -- before umask, open, dup2,
	 * backtrace_symbols_fd, write_siginfo_safely, or anything else
	 * libc-touchy.  When the underlying root cause is a corrupted
	 * ld.so writable segment (NULL'd link_map slot, stomped GOT), the
	 * very next backtrace_symbols_fd call re-faults inside dladdr's
	 * link_map walk and the process dies before any forensic line
	 * lands on disk.  The beacon captures the death class into shared
	 * memory using only kernel-supplied siginfo + ucontext fields and
	 * a local-then-publish struct copy -- no allocator, no stdio, no
	 * lock -- so the parent's dump_child_fault_beacon() can surface
	 * the silenced class even in the re-fault case.  See
	 * include/bug_backtrace.h::child_fault_beacon for the field
	 * contract and the release-store / acquire-load handoff that
	 * orders the stamp into the parent's view.
	 */
	{
		struct childdata *me = this_child();

		if (me != NULL) {
			struct child_fault_beacon *beacon = &me->fault_beacon;
			struct child_fault_beacon local;
			enum syscallstate st = me->syscall.state;
			int32_t snr;

			if (st == PREP || st == BEFORE || st == GOING_AWAY)
				snr = (int32_t)me->syscall.nr;
			else
				snr = -1;
			/*
			 * Build the stamp on the stack first, then publish
			 * the whole record via a single struct assignment.
			 *
			 * fault_sa in mask_signals_child() installs this
			 * handler with sa_mask = empty and no SA_NODEFER on
			 * SIGABRT/SIGBUS/SIGILL, so a different fatal signal
			 * delivered mid-stamp can run an inner copy of this
			 * handler to completion.  If we stamped field-by-
			 * field directly into the shared slot, the inner
			 * handler would publish a full record (its own
			 * release-store of .written = 1) and the outer
			 * handler's resumed plain stores would then overwrite
			 * the shared fields piecemeal, leaving a torn
			 * forensic line (signo from one fault, ip/sp from
			 * another) for the parent's acquire-load to read.
			 *
			 * With local-then-publish: an inner handler that
			 * runs to completion publishes its own self-
			 * consistent record; when the outer handler resumes,
			 * the single struct assignment from this stack
			 * snapshot rewrites the shared slot with a self-
			 * consistent outer record before the trailing
			 * release-store of .written = 1 seals it.  Either
			 * way the parent never observes a mixed record.
			 *
			 * .written is left zero in the local so the struct
			 * assignment transiently clears the published bit;
			 * the release-store below is the real publish edge.
			 */
			local.written = 0;
			local.signo = (int32_t)sig;
			local.sig_code = (int32_t)info->si_code;
			local.fault_addr = info->si_addr;
			local.fault_ip = fault_beacon_extract_ip(ctx);
			local.fault_sp = fault_beacon_extract_sp(ctx);
			local.op_nr = me->op_nr;
			local.last_syscall_nr = snr;
			*beacon = local;
			/* Release-store seals every preceding plain store
			 * into view of any parent that acquire-loads
			 * .written and sees 1. */
			__atomic_store_n(&beacon->written, 1U,
					 __ATOMIC_RELEASE);
		}
	}
	/*
	 * Reset the umask before the kernel / userspace coredump helper
	 * creates the core file (raise(sig) below with SIG_DFL under
	 * debug mode).  The umask syscall is itself fuzzed, so a child
	 * that drew umask(0777) and then crashed would otherwise have
	 * its core file created with mode 0666 & ~0777 == 0, and the
	 * helper would abort with "cannot preserve file permissions".
	 * The per-pid bug log itself is no longer created here -- stderr
	 * was pre-redirected to it in init_child_isolate_io() under the
	 * inherited (non-fuzzed) umask, and the writes below all flow
	 * through STDERR_FILENO.  umask() is async-signal-safe (POSIX
	 * 2024 §2.4.3) so this is safe to call from a signal handler.
	 * Returning the old mask is intentionally ignored — this child
	 * is about to die.
	 */
	(void)umask(0);
#if defined(USE_BACKTRACE) && !defined(__SANITIZE_ADDRESS__)
	{
		void *frames[64];
		int nframes = backtrace(frames, 64);

		backtrace_symbols_fd(frames, nframes, STDERR_FILENO);
	}
#endif
	write_siginfo_safely(sig, info, "trinity child");

	/*
	 * Capture glibc's last-gasp explanation before SIGABRT.  Glibc's
	 * malloc_printerr / __libc_message / __stack_chk_fail /
	 * __fortify_fail family stash a NUL-terminated formatted
	 * complaint into a process-global __abort_msg pointer and then
	 * raise(SIGABRT).  Reading it here turns 200+ undifferentiated
	 * "abort at malloc+0x150" bugs into bucketed corruption-mode
	 * lines like "free(): double free detected in tcache 2" right
	 * at the top of the bug log.
	 *
	 * glibc_abort_msg_p was resolved once at child init via
	 * dlvsym(RTLD_DEFAULT, "__abort_msg", "GLIBC_PRIVATE") with a
	 * dlsym() fallback -- see init_abort_msg_capture() above.  No
	 * link-time GLIBC_PRIVATE version dependency; a future glibc
	 * that drops the symbol leaves the cached pointer NULL and the
	 * capture silently skips.  The handler does one plain load
	 * through the cached pointer (signal-safe), a NULL check on
	 * the contents, and a write().
	 *
	 * The inner pointer is NULL when abort() was reached from user
	 * code rather than a libc self-check, so guard on both the
	 * cached lookup pointer and the contents.  The message text
	 * lives at offset +4 inside the struct (past the size field).
	 */
	if (sig == SIGABRT && glibc_abort_msg_p != NULL) {
		struct abort_msg_s *m = *glibc_abort_msg_p;

		if (m != NULL) {
			char buf[512];
			struct sigsafe_buf b = { buf, sizeof(buf) };
			ssize_t w;

			sigsafe_puts(&b, "abort_msg: ");
			sigsafe_puts(&b, m->msg);
			sigsafe_putc(&b, '\n');
			w = write(STDERR_FILENO, buf, sizeof(buf) - b.left);
			(void)w;	/* dying anyway; can't act on a short write */
		}
	}

	/*
	 * Stamp the currently-running childop's identity into the per-pid
	 * bug log so the canary queue (and post-mortem grep-mining) can
	 * attribute a SIGSEGV/SIGBUS/SIGILL/SIGABRT to a specific op
	 * rather than bottoming out at child_process+offset like the bare
	 * libgcc backtrace does.  this_child() reads a plain pointer set
	 * once per child in init_child() (see pids.c::set_child_cache);
	 * alt_op_name() is a pure switch over an enum with no allocation
	 * or locking.  Both are safe to call from this handler.
	 *
	 * Hand-roll the formatter rather than dprintf() so the write is a
	 * single syscall and uses no stdio buffering -- mirrors the
	 * write_siginfo_safely() pattern just above.  PATH_MAX is
	 * comfortably oversized for "childop=<longest-name> op_nr=<ulong>
	 * last_syscall_nr=<int>\n".
	 *
	 * last_syscall_nr is the in-flight syscall number sourced from
	 * me->syscall.nr -- the per-child syscallrecord embedded in
	 * childdata, populated by set_syscall_nr() before each dispatch.
	 * Reading a plain unsigned int from process-local shm-resident
	 * memory is async-signal-safe (no allocation, no lock, no table
	 * lookup).  We emit the NUMBER rather than the name because the
	 * number->name map (get_syscall_entry / syscalls[].name) is a
	 * pointer-chasing table walk that is not on the POSIX async-
	 * signal-safe list; the bugs.txt post-parser can resolve names
	 * offline.
	 *
	 * We gate on me->syscall.state to avoid emitting a stale number
	 * when the signal hit between syscalls.  rec->nr is only meaning-
	 * fully populated once set_syscall_nr() has run for the current
	 * iteration; states UNKNOWN (child just started, never picked) and
	 * AFTER (previous call returned, next not yet picked) both mean
	 * "no syscall in flight".  In those cases we emit -1 rather than a
	 * misleading number that points at the *previous* call.
	 */
	{
		struct childdata *me = this_child();
		const char *opname;
		unsigned long opnr;
		int last_syscall_nr;
		char buf[160];

		if (me != NULL) {
			enum syscallstate st = me->syscall.state;

			opname = alt_op_name(me->op_type);
			opnr = me->op_nr;
			if (opname == NULL)
				opname = "unknown";
			if (st == PREP || st == BEFORE || st == GOING_AWAY)
				last_syscall_nr = (int)me->syscall.nr;
			else
				last_syscall_nr = -1;
		} else {
			opname = "unknown";
			opnr = 0;
			last_syscall_nr = -1;
		}
		{
			struct sigsafe_buf b = { buf, sizeof(buf) };
			size_t used;
			ssize_t w;

			sigsafe_puts(&b, "childop=");
			sigsafe_puts(&b, opname);
			sigsafe_puts(&b, " op_nr=");
			sigsafe_putu(&b, opnr);
			sigsafe_puts(&b, " last_syscall_nr=");
			sigsafe_puti(&b, (long)last_syscall_nr);
			sigsafe_putc(&b, '\n');

			used = sizeof(buf) - b.left;
			w = write(STDERR_FILENO, buf, used);
			(void)w;	/* dying anyway; nothing to do on short write */
		}
	}

	if (shm->debug == true) {
		(void)signal(sig, SIG_DFL);
		raise(sig);
	} else {
		_exit(EXIT_SUCCESS);
	}
}

static void sigalrm_handler(__unused__ int sig)
{
	sigalrm_pending = 1;
	/* Don't siglongjmp here.  SIGALRM is installed without
	 * SA_RESTART, so the signal interrupts the blocking syscall
	 * (it returns EINTR/ERESTARTNOHAND) and control returns to
	 * the child main loop where sigalrm_pending is checked.
	 *
	 * The old code called siglongjmp() from here, which could
	 * permanently leak glibc's allocator lock if the child was
	 * inside malloc/free at signal delivery time, causing
	 * deadlock or heap corruption on the next allocation. */
}

static void sigxcpu_handler(__unused__ int sig)
{
	xcpu_pending = 1;
	/* Don't siglongjmp here.  The signal interrupts the syscall
	 * (SIGXCPU is installed without SA_RESTART), and the child
	 * main loop checks xcpu_pending on the next iteration.
	 * Longjmping from here risked orphaning locks held at the
	 * time of the signal. */
}

/*
 * Handler for signals that should only be fatal if they come from the
 * kernel (real fault), not from a child process sending us garbage via
 * kill/tkill/tgkill.
 *
 * si_code > 0:  kernel generated (e.g. SEGV_MAPERR) — always fatal
 * si_code <= 0: sent by a process (SI_USER, SI_TKILL, SI_QUEUE)
 *   - from ourselves (abort(), raise()): fatal — it's a real crash
 *   - from a child process: ignore — it's fuzzer noise
 */
static __attribute__((no_sanitize("address")))
void main_fault_handler(int sig, siginfo_t *info, __unused__ void *ctx)
{
	if (info->si_code > 0 || info->si_pid == mypid()) {
		/* Real fault or self-sent (e.g. glibc abort) — dump a
		 * backtrace and siginfo to stderr first so we have a handle
		 * on the crash even when no coredump lands (ulimit -c 0 or a
		 * restrictive core_pattern), then die properly. */
#if defined(USE_BACKTRACE) && !defined(__SANITIZE_ADDRESS__)
		void *frames[64];
		int nframes = backtrace(frames, 64);
		backtrace_symbols_fd(frames, nframes, STDERR_FILENO);
#endif
		write_siginfo_safely(sig, info, "trinity main");
		signal(sig, SIG_DFL);
		raise(sig);
	}
	/* Sent by a child process — ignore */
}

void mask_signals_child(void)
{
	struct sigaction sa;
	sigset_t ss, oldss;
	int i;

	/* Block all signals while we install handlers.  Without this,
	 * a signal arriving between the catch-all sighandler install
	 * and the proper handler install would silently _exit(SUCCESS),
	 * masking the real cause of the child's death. */
	sigfillset(&ss);
	sigprocmask(SIG_BLOCK, &ss, &oldss);

	for (i = 1; i < _NSIG; i++) {
		(void)sigfillset(&ss);
		sa.sa_flags = SA_RESTART;
		sa.sa_handler = sighandler;
		sa.sa_mask = ss;
		(void)sigaction(i, &sa, NULL);
	}
	/* we want default behaviour for child process signals */
	(void)signal(SIGCHLD, SIG_DFL);

	/* SIGALRM: set a flag and let the interrupted syscall return
	 * EINTR.  Installed without SA_RESTART so blocking syscalls
	 * are interrupted rather than silently restarted. */
	{
		struct sigaction alrm_sa;
		sigemptyset(&alrm_sa.sa_mask);
		alrm_sa.sa_flags = 0;
		alrm_sa.sa_handler = sigalrm_handler;
		(void)sigaction(SIGALRM, &alrm_sa, NULL);
	}

	/* Count SIGXCPUs.  Install without SA_RESTART so the signal
	 * interrupts blocking syscalls and control returns to the
	 * child main loop where xcpu_pending is checked. */
	{
		struct sigaction xcpu_sa;
		sigemptyset(&xcpu_sa.sa_mask);
		xcpu_sa.sa_flags = 0;
		xcpu_sa.sa_handler = sigxcpu_handler;
		(void)sigaction(SIGXCPU, &xcpu_sa, NULL);
	}

	/* ignore signals we don't care about */
	(void)signal(SIGFPE, SIG_IGN);
	(void)signal(SIGTSTP, SIG_IGN);
	(void)signal(SIGWINCH, SIG_IGN);
	(void)signal(SIGIO, SIG_IGN);
	(void)signal(SIGPIPE, SIG_IGN);
	(void)signal(SIGXFSZ, SIG_IGN);

	/* Ignore the RT signals. */
	for (i = SIGRTMIN; i <= SIGRTMAX; i++)
		(void)signal(i, SIG_IGN);

	/*
	 * Install child_fault_handler for the kernel-fault signals.
	 * Replaces both the catch-all sighandler (which silently
	 * _exit'd, masking the cause) and the debug-mode SIG_DFL
	 * override (which dumped a core but no inline backtrace).
	 * The handler dumps a backtrace + psiginfo to stderr in BOTH
	 * modes; in debug it then re-raises with SIG_DFL so the kernel
	 * still drops a core, in non-debug it _exit's cleanly so the
	 * parent's reaper doesn't see a crash and crash-loop.
	 */
	{
		struct sigaction fault_sa;
		sigemptyset(&fault_sa.sa_mask);
		fault_sa.sa_flags = SA_SIGINFO;
		fault_sa.sa_sigaction = child_fault_handler;
		(void)sigaction(SIGSEGV, &fault_sa, NULL);
		(void)sigaction(SIGABRT, &fault_sa, NULL);
		(void)sigaction(SIGBUS,  &fault_sa, NULL);
		(void)sigaction(SIGILL,  &fault_sa, NULL);
	}

	/* trap ctrl-c — use SA_SIGINFO so we can ignore child-sent SIGINTs,
	 * same as the parent handler. Without this, children fuzzing
	 * rt_tgsigqueueinfo/kill with SIGINT cause phantom ctrl-c exits. */
	{
		struct sigaction int_sa;
		sigemptyset(&int_sa.sa_mask);
		int_sa.sa_flags = SA_SIGINFO;
		int_sa.sa_sigaction = sigint_handler;
		(void)sigaction(SIGINT, &int_sa, NULL);
	}

	/* All handlers installed — unblock signals. */
	sigprocmask(SIG_SETMASK, &oldss, NULL);
}


void setup_main_signals(void)
{
	struct sigaction sa;
	int i;

	(void)signal(SIGCHLD, SIG_DFL);

	/*
	 * Ignore signals that children can send us via kill/tkill/tgkill.
	 * Without this, the fuzzer randomly terminates when a child happens
	 * to send a fatal signal to the parent PID.
	 */
	(void)signal(SIGHUP, SIG_IGN);
	(void)signal(SIGUSR1, SIG_IGN);
	(void)signal(SIGUSR2, SIG_IGN);
	(void)signal(SIGALRM, SIG_IGN);
	(void)signal(SIGTERM, SIG_IGN);
	(void)signal(SIGVTALRM, SIG_IGN);
	(void)signal(SIGPROF, SIG_IGN);
	(void)signal(SIGXFSZ, SIG_IGN);
	(void)signal(SIGXCPU, SIG_IGN);
	(void)signal(SIGPIPE, SIG_IGN);
	(void)signal(SIGIO, SIG_IGN);

	/* Ignore RT signals — children fuzzing rt_sigqueueinfo,
	 * pidfd_send_signal, timer_create/settime with sigev_signo in
	 * [SIGRTMIN..SIGRTMAX], etc. can deliver any RT signal to us.
	 * Default kernel action for an unhandled RT signal is termination,
	 * which silently exits trinity ("Real-time signal N" printed by
	 * glibc).  Mirror the same loop the children use in mask_signals_child. */
	for (i = SIGRTMIN; i <= SIGRTMAX; i++)
		(void)signal(i, SIG_IGN);

	/*
	 * Use SA_SIGINFO for fault/core-dump signals so we can distinguish
	 * real faults (si_code > 0, from kernel) from signals sent by child
	 * processes fuzzing kill/tkill/tgkill (si_code <= 0).
	 */
	sigemptyset(&sa.sa_mask);
	sa.sa_flags = SA_SIGINFO;
	sa.sa_sigaction = main_fault_handler;
	(void)sigaction(SIGABRT, &sa, NULL);
	(void)sigaction(SIGSEGV, &sa, NULL);
	(void)sigaction(SIGBUS, &sa, NULL);
	(void)sigaction(SIGILL, &sa, NULL);
	(void)sigaction(SIGFPE, &sa, NULL);
	(void)sigaction(SIGQUIT, &sa, NULL);
	(void)sigaction(SIGTRAP, &sa, NULL);
	(void)sigaction(SIGSYS, &sa, NULL);

	/* SIGINT: use SA_SIGINFO so we can ignore child-sent SIGINTs.
	 * Real ctrl-c from the terminal has si_code > 0 (SI_KERNEL). */
	sa.sa_sigaction = sigint_handler;
	(void)sigaction(SIGINT, &sa, NULL);

	/*
	 * Eager-load libgcc_s.so.1 by calling backtrace() once now, while
	 * malloc is healthy and no fault handler can fire.  The first
	 * backtrace() in a process triggers
	 *   libc_unwind_link_get -> __libc_dlopen_mode("libgcc_s.so.1")
	 *     -> _dl_load_cache_lookup -> strdup -> malloc
	 * If we instead reach backtrace() for the first time from the
	 * SIGABRT handler raised by a glibc malloc assertion (heap
	 * corruption -> abort), the main_arena lock is already held by
	 * this very thread.  The recursive malloc inside dlopen then
	 * deadlocks forever in lll_lock_wait_private and we lose every
	 * child to a futex_wait we cannot recover from -- the diagnostic
	 * machinery itself becomes the bug.
	 *
	 * Doing it here, in the parent before fork, ensures libgcc_s is
	 * already mapped in every child via copy-on-write inheritance, so
	 * neither child_fault_handler nor main_fault_handler can hit the
	 * dlopen path at signal time.
	 */
#if defined(USE_BACKTRACE) && !defined(__SANITIZE_ADDRESS__)
	{
		void *stub[1];
		(void)backtrace(stub, 1);
	}
#endif
}
