/* Syscalls from arch/powerpc/include/asm/systbl.h as of 2.6.31rc2 */

#include "trinity.h"
#include "sanitise.h"

#include <fcntl.h>
#include <signal.h>
#include <asm/mman.h>

# define NR_SYSCALLS 322

struct syscalltable syscalls_ppc[NR_SYSCALLS+1] = {
#include "syscalls/restart_syscall.h"
#include "syscalls/exit.h"
#include "syscalls/fork.h"
#include "syscalls/read.h"
#include "syscalls/write.h"
#include "syscalls/open.h"
#include "syscalls/close.h"
#include "syscalls/waitpid.h"
#include "syscalls/creat.h"
#include "syscalls/link.h"
#include "syscalls/unlink.h"
#include "syscalls/execve.h"
#include "syscalls/chdir.h"
#include "syscalls/time.h"
#include "syscalls/mknod.h"
#include "syscalls/chmod.h"
#include "syscalls/lchown.h"
#include "syscalls/old_break.h"
#include "syscalls/stat.h"
#include "syscalls/lseek.h"
#include "syscalls/getpid.h"
#include "syscalls/mount.h"
#include "syscalls/oldumount.h"
#include "syscalls/setuid.h"
#include "syscalls/getuid.h"
#include "syscalls/stime.h"
#include "syscalls/ptrace.h"
#include "syscalls/alarm.h"
#include "syscalls/ni_syscall.h" // was OLDSYS(fstat)
#include "syscalls/pause.h"
#include "syscalls/utime.h"
#include "syscalls/ni_syscall.h" // (old stty syscall holder).h
#include "syscalls/ni_syscall.h" // (old gtty syscall holder).h
#include "syscalls/access.h"
#include "syscalls/nice.h"
#include "syscalls/ni_syscall.h" // old ftime syscall holder
#include "syscalls/sync.h"
#include "syscalls/kill.h"
#include "syscalls/rename.h"
#include "syscalls/mkdir.h"
#include "syscalls/rmdir.h"
#include "syscalls/dup.h"
#include "syscalls/pipe.h"
#include "syscalls/times.h"
#include "syscalls/ni_syscall.h" // (old prof syscall holder)
#include "syscalls/brk.h"
#include "syscalls/setgid.h"
#include "syscalls/getgid.h"
#include "syscalls/signal.h"
#include "syscalls/geteuid.h"
#include "syscalls/getegid.h"
#include "syscalls/acct.h"
#include "syscalls/umount.h" // recycled never used phys()
#include "syscalls/ni_syscall.h" // old lock syscall holder
#include "syscalls/ioctl.h"
#include "syscalls/fcntl.h"
#include "syscalls/ni_syscall.h" // old mpx syscall holder
#include "syscalls/setpgid.h"
#include "syscalls/ni_syscall.h" // old ulimit syscall holder
#include "syscalls/olduname.h"
#include "syscalls/umask.h"
#include "syscalls/chroot.h"
#include "syscalls/ustat.h"
#include "syscalls/dup2.h"
#include "syscalls/getppid.h"
#include "syscalls/getpgrp.h"
#include "syscalls/setsid.h"
#include "syscalls/sigaction.h"
#include "syscalls/sgetmask.h"
#include "syscalls/ssetmask.h"
#include "syscalls/setreuid.h"
#include "syscalls/setregid.h"
#include "syscalls/sigsuspend.h"
#include "syscalls/sigpending.h"
#include "syscalls/sethostname.h"
#include "syscalls/setrlimit.h"
#include "syscalls/ni_syscall.h" // was COMPAT_SYS(old_getrlimit)
#include "syscalls/getrusage.h"
#include "syscalls/gettimeofday.h"
#include "syscalls/settimeofday.h"
#include "syscalls/getgroups.h"
#include "syscalls/setgroups.h"
#include "syscalls/select.h"
#include "syscalls/symlink.h"
#include "syscalls/lstat.h"
#include "syscalls/readlink.h"
#include "syscalls/uselib.h"
#include "syscalls/swapon.h"
#include "syscalls/reboot.h"
#include "syscalls/oldreaddir.h"
#include "syscalls/mmap.h"
#include "syscalls/munmap.h"
#include "syscalls/truncate.h"
#include "syscalls/ftruncate.h"
#include "syscalls/fchmod.h"
#include "syscalls/fchown.h"
#include "syscalls/getpriority.h"
#include "syscalls/setpriority.h"
#include "syscalls/ni_syscall.h" // old profil syscall holder
#include "syscalls/statfs.h"
#include "syscalls/fstatfs.h"
#include "syscalls/ni_syscall.h"
#include "syscalls/socketcall.h"
#include "syscalls/syslog.h"
#include "syscalls/setitimer.h"
#include "syscalls/getitimer.h"
#include "syscalls/newstat.h"
#include "syscalls/newlstat.h"
#include "syscalls/newfstat.h"
#include "syscalls/uname.h"
#include "syscalls/ni_syscall.h" // (105)"
#include "syscalls/vhangup.h"
#include "syscalls/ni_syscall.h" // old 'idle' system call?
#include "syscalls/ni_syscall.h" // 108
#include "syscalls/wait4.h"
#include "syscalls/swapoff.h"
#include "syscalls/sysinfo.h"
#include "syscalls/ipc.h"
#include "syscalls/fsync.h"
#include "syscalls/sigreturn.h"
#include "syscalls/clone.h"
#include "syscalls/setdomainname.h"
#include "syscalls/newuname.h"
#include "syscalls/ni_syscall.h"
#include "syscalls/adjtimex.h"
#include "syscalls/mprotect.h"
#include "syscalls/sigprocmask.h"
#include "syscalls/ni_syscall.h" // old create module
#include "syscalls/init_module.h"
#include "syscalls/delete_module.h"
#include "syscalls/ni_syscall.h" // old get_kernel_syms
#include "syscalls/quotactl.h"
#include "syscalls/getpgid.h"
#include "syscalls/fchdir.h"
#include "syscalls/bdflush.h"
#include "syscalls/sysfs.h"
#include "syscalls/personality.h"
#include "syscalls/afs.h"
#include "syscalls/setfsuid.h"
#include "syscalls/setfsgid.h"
#include "syscalls/llseek.h"
#include "syscalls/getdents.h"
#include "syscalls/select.h"
#include "syscalls/flock.h"
#include "syscalls/msync.h"
#include "syscalls/readv.h"
#include "syscalls/writev.h"
#include "syscalls/getsid.h"
#include "syscalls/fdatasync.h"
#include "syscalls/sysctl.h"
#include "syscalls/mlock.h"
#include "syscalls/munlock.h"
#include "syscalls/mlockall.h"
#include "syscalls/munlockall.h"
#include "syscalls/sched_setparam.h"
#include "syscalls/sched_getparam.h"
#include "syscalls/sched_setscheduler.h"
#include "syscalls/sched_getscheduler.h"
#include "syscalls/sched_yield.h"
#include "syscalls/sched_get_priority_max.h"
#include "syscalls/sched_get_priority_min.h"
#include "syscalls/sched_rr_get_interval.h"
#include "syscalls/nanosleep.h"
#include "syscalls/mremap.h"
#include "syscalls/setresuid.h"
#include "syscalls/getresuid.h"
#include "syscalls/ni_syscall.h" // Old sys_query_module
#include "syscalls/poll.h"
#include "syscalls/nfsservctl.h"
#include "syscalls/setresgid.h"
#include "syscalls/getresgid.h"
#include "syscalls/prctl.h"
#include "syscalls/rt_sigreturn.h"
#include "syscalls/rt_sigaction.h"
#include "syscalls/rt_sigprocmask.h"
#include "syscalls/rt_sigpending.h"
#include "syscalls/rt_sigtimedwait.h"
#include "syscalls/rt_sigqueueinfo.h"
#include "syscalls/rt_sigsuspend.h"
#include "syscalls/pread64.h"
#include "syscalls/pwrite64.h"
#include "syscalls/chown.h"
#include "syscalls/getcwd.h"
#include "syscalls/capget.h"
#include "syscalls/capset.h"
#include "syscalls/sigaltstack.h"
#include "syscalls/sendfile.h"
#include "syscalls/ni_syscall.h" // reserved for streams1
#include "syscalls/ni_syscall.h" // reserved for streams2
#include "syscalls/vfork.h"
#include "syscalls/getrlimit.h"
#include "syscalls/readahead.h"
#include "syscalls/mmap.h"
#include "syscalls/truncate64.h"
#include "syscalls/ftruncate64.h"
#include "syscalls/stat64.h"
#include "syscalls/lstat64.h"
#include "syscalls/fstat64.h"
#include "syscalls/ni_syscall.h" // TODO: pciconfig_read
#include "syscalls/ni_syscall.h" // TODO: pciconfig_write
#include "syscalls/ni_syscall.h" // TODO: pciconfig_iobase
#include "syscalls/ni_syscall.h" // 201
#include "syscalls/getdents64.h"
#include "syscalls/pivot_root.h"
#include "syscalls/fcntl64.h"
#include "syscalls/madvise.h"
#include "syscalls/mincore.h"
#include "syscalls/gettid.h"
#include "syscalls/tkill.h"
#include "syscalls/setxattr.h"
#include "syscalls/lsetxattr.h"
#include "syscalls/fsetxattr.h"
#include "syscalls/getxattr.h"
#include "syscalls/lgetxattr.h"
#include "syscalls/fgetxattr.h"
#include "syscalls/listxattr.h"
#include "syscalls/llistxattr.h"
#include "syscalls/flistxattr.h"
#include "syscalls/removexattr.h"
#include "syscalls/lremovexattr.h"
#include "syscalls/fremovexattr.h"
#include "syscalls/futex.h"
#include "syscalls/sched_setaffinity.h"
#include "syscalls/sched_getaffinity.h"
#include "syscalls/ni_syscall.h"
#include "syscalls/ni_syscall.h"
#include "syscalls/sendfile64.h"
#include "syscalls/io_setup.h"
#include "syscalls/io_destroy.h"
#include "syscalls/io_getevents.h"
#include "syscalls/io_submit.h"
#include "syscalls/io_cancel.h"
#include "syscalls/set_tid_address.h"
#include "syscalls/fadvise64.h"
#include "syscalls/exit_group.h"
#include "syscalls/lookup_dcookie.h"
#include "syscalls/epoll_create.h"
#include "syscalls/epoll_ctl.h"
#include "syscalls/epoll_wait.h"
#include "syscalls/remap_file_pages.h"
#include "syscalls/timer_create.h"
#include "syscalls/timer_settime.h"
#include "syscalls/timer_gettime.h"
#include "syscalls/timer_getoverrun.h"
#include "syscalls/timer_delete.h"
#include "syscalls/clock_settime.h"
#include "syscalls/clock_gettime.h"
#include "syscalls/clock_getres.h"
#include "syscalls/clock_nanosleep.h"
#include "syscalls/ni_syscall.h" // TODO: ppc64_swapcontext
#include "syscalls/tgkill.h"
#include "syscalls/utimes.h"
#include "syscalls/statfs64.h"
#include "syscalls/fstatfs64.h"
#include "syscalls/fadvise64_64.h"
#include "syscalls/rtas.h"
#include "syscalls/ni_syscall.h" // TODO: debug_setcontext
#include "syscalls/ni_syscall.h"
#include "syscalls/migrate_pages.h"
#include "syscalls/mbind.h"
#include "syscalls/get_mempolicy.h"
#include "syscalls/set_mempolicy.h"
#include "syscalls/mq_open.h"
#include "syscalls/mq_unlink.h"
#include "syscalls/mq_timedsend.h"
#include "syscalls/mq_timedreceive.h"
#include "syscalls/mq_notify.h"
#include "syscalls/mq_getsetattr.h"
#include "syscalls/kexec_load.h"
#include "syscalls/add_key.h"
#include "syscalls/request_key.h"
#include "syscalls/keyctl.h"
#include "syscalls/waitid.h"
#include "syscalls/ioprio_set.h"
#include "syscalls/ioprio_get.h"
#include "syscalls/inotify_init.h"
#include "syscalls/inotify_add_watch.h"
#include "syscalls/inotify_rm_watch.h"
#include "syscalls/ni_syscall.h" // TODO: spu_run
#include "syscalls/ni_syscall.h" // TODO: spu_create
#include "syscalls/pselect6.h"
#include "syscalls/ppoll.h"
#include "syscalls/unshare.h"
#include "syscalls/splice.h"
#include "syscalls/tee.h"
#include "syscalls/vmsplice.h"
#include "syscalls/openat.h"
#include "syscalls/mkdirat.h"
#include "syscalls/mknodat.h"
#include "syscalls/fchownat.h"
#include "syscalls/futimesat.h"
#include "syscalls/fstatat64.h"
#include "syscalls/unlinkat.h"
#include "syscalls/renameat.h"
#include "syscalls/linkat.h"
#include "syscalls/symlinkat.h"
#include "syscalls/readlinkat.h"
#include "syscalls/fchmodat.h"
#include "syscalls/faccessat.h"
#include "syscalls/get_robust_list.h"
#include "syscalls/set_robust_list.h"
#include "syscalls/move_pages.h"
#include "syscalls/getcpu.h"
#include "syscalls/epoll_pwait.h"
#include "syscalls/utimensat.h"
#include "syscalls/signalfd.h"
#include "syscalls/timerfd_create.h"
#include "syscalls/eventfd.h"
#include "syscalls/sync_file_range2.h"
#include "syscalls/fallocate.h"
#include "syscalls/ni_syscall.h" // TODO: subpage_prot
#include "syscalls/timerfd_settime.h"
#include "syscalls/timerfd_gettime.h"
#include "syscalls/signalfd4.h"
#include "syscalls/eventfd2.h"
#include "syscalls/epoll_create1.h"
#include "syscalls/dup3.h"
#include "syscalls/pipe2.h"
#include "syscalls/inotify_init1.h"
#include "syscalls/perf_counter_open.h"
#include "syscalls/preadv.h"
#include "syscalls/pwritev.h"
#include "syscalls/rt_tgsigqueueinfo.h"
};
