/*
 *   SYSCALL_DEFINE4(io_uring_register, unsigned int, fd, unsigned int, opcode, void __user *, arg, unsigned int, nr_args)
 */
#include "sanitise.h"

/* io_uring_register opcodes */
#define IORING_REGISTER_BUFFERS			0
#define IORING_UNREGISTER_BUFFERS		1
#define IORING_REGISTER_FILES			2
#define IORING_UNREGISTER_FILES			3
#define IORING_REGISTER_EVENTFD			4
#define IORING_UNREGISTER_EVENTFD		5
#define IORING_REGISTER_FILES_UPDATE		6
#define IORING_REGISTER_EVENTFD_ASYNC		7
#define IORING_REGISTER_PROBE			8
#define IORING_REGISTER_PERSONALITY		9
#define IORING_UNREGISTER_PERSONALITY		10
#define IORING_REGISTER_RESTRICTIONS		11
#define IORING_REGISTER_ENABLE_RINGS		12
#define IORING_REGISTER_FILES2			13
#define IORING_REGISTER_FILES_UPDATE2		14
#define IORING_REGISTER_BUFFERS2		15
#define IORING_REGISTER_BUFFERS_UPDATE		16
#define IORING_REGISTER_IOWQ_AFF		17
#define IORING_UNREGISTER_IOWQ_AFF		18
#define IORING_REGISTER_IOWQ_MAX_WORKERS	19
#define IORING_REGISTER_RING_FDS		20
#define IORING_UNREGISTER_RING_FDS		21
#define IORING_REGISTER_PBUF_RING		22
#define IORING_UNREGISTER_PBUF_RING		23
#define IORING_REGISTER_SYNC_CANCEL		24
#define IORING_REGISTER_FILE_ALLOC_RANGE	25
#define IORING_REGISTER_PBUF_STATUS		26
#define IORING_REGISTER_NAPI			27
#define IORING_UNREGISTER_NAPI			28
#define IORING_REGISTER_CLOCK			29
#define IORING_REGISTER_CLONE_BUFFERS		30
#define IORING_REGISTER_RESIZE_RINGS		31
#define IORING_REGISTER_MEM_REGION		32
#define IORING_UNREGISTER_MEM_REGION		33
#define IORING_REGISTER_ZCRX_IFQ		34
#define IORING_REGISTER_ZCRX_RX		35
#define IORING_REGISTER_ZCRX_CTRL		36

static unsigned long io_uring_register_opcodes[] = {
	IORING_REGISTER_BUFFERS,
	IORING_UNREGISTER_BUFFERS,
	IORING_REGISTER_FILES,
	IORING_UNREGISTER_FILES,
	IORING_REGISTER_EVENTFD,
	IORING_UNREGISTER_EVENTFD,
	IORING_REGISTER_FILES_UPDATE,
	IORING_REGISTER_EVENTFD_ASYNC,
	IORING_REGISTER_PROBE,
	IORING_REGISTER_PERSONALITY,
	IORING_UNREGISTER_PERSONALITY,
	IORING_REGISTER_RESTRICTIONS,
	IORING_REGISTER_ENABLE_RINGS,
	IORING_REGISTER_FILES2,
	IORING_REGISTER_FILES_UPDATE2,
	IORING_REGISTER_BUFFERS2,
	IORING_REGISTER_BUFFERS_UPDATE,
	IORING_REGISTER_IOWQ_AFF,
	IORING_UNREGISTER_IOWQ_AFF,
	IORING_REGISTER_IOWQ_MAX_WORKERS,
	IORING_REGISTER_RING_FDS,
	IORING_UNREGISTER_RING_FDS,
	IORING_REGISTER_PBUF_RING,
	IORING_UNREGISTER_PBUF_RING,
	IORING_REGISTER_SYNC_CANCEL,
	IORING_REGISTER_FILE_ALLOC_RANGE,
	IORING_REGISTER_PBUF_STATUS,
	IORING_REGISTER_NAPI,
	IORING_UNREGISTER_NAPI,
	IORING_REGISTER_CLOCK,
	IORING_REGISTER_CLONE_BUFFERS,
	IORING_REGISTER_RESIZE_RINGS,
	IORING_REGISTER_MEM_REGION,
	IORING_UNREGISTER_MEM_REGION,
	IORING_REGISTER_ZCRX_IFQ,
	IORING_REGISTER_ZCRX_RX,
	IORING_REGISTER_ZCRX_CTRL,
};

struct syscallentry syscall_io_uring_register = {
	.name = "io_uring_register",
	.num_args = 4,
	.arg1name = "fd",
	.arg1type = ARG_FD,
	.arg2name = "opcode",
	.arg2type = ARG_OP,
	.arg2list = ARGLIST(io_uring_register_opcodes),
	.arg3name = "arg",
	.arg3type = ARG_ADDRESS,
	.arg4name = "nr_args",
};
