/*
 * Help/usage output for the params cluster.  option_descs[] and
 * shortonly_descs[] are the single source of truth for the --help
 * text; longopts[] in options.c is the getopt_long() metadata that
 * mirrors them and dispatches into the parse_*_options() helpers.
 * Adding an option means touching both tables (plus a parser helper).
 */

#include <ctype.h>
#include <errno.h>
#include <getopt.h>
#include <limits.h>
#include <sys/resource.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "arg-len-semantics.h"
#include "bdevs.h"
#include "child.h"
#include "blob_mutator.h"
#include "cmp-frontier.h"
#include "cmp_hints.h"
#include "cmsg-richness.h"
#include "fd.h"
#include "kcov.h"
#include "net.h"
#include "params.h"
#include "domains.h"
#include "random.h"
#include "reach-band.h"
#include "self_cgroup.h"
#include "strategy.h"
#include "syscall.h"
#include "tables.h"
#include "taint.h"
#include "trinity.h"	// progname, max_files_rlimit
#include "utils.h"

#include "kernel/hw_breakpoint.h"
#include "kernel/socket.h"

#include "internal.h"

struct option_help {
	const char *name;	/* long option name (NULL = end of table) */
	char shortopt;		/* short option char, or 0 if none */
	const char *desc;	/* help text */
};

static const struct option_help option_descs[] = {
	{ "alt-op-children",	 0,  "reserve N children to run dedicated alt ops (mmap_lifecycle, mprotect_split, ...) round-robin instead of mixing them at 1% in every child (default: max(2, --children/8))" },
	{ "arch",		'a', "selects syscalls for the specified architecture (32 or 64). Both by default." },
	{ "blob-mutator",	 0,  "content-authoring lane for opaque ARG_BUF_SIZED args (default off): off (the ARG_BUF_SIZED hook skips blob_fill() entirely -- no mode-load past the early return, no RNG draw, no byte write; fixed-seed runs reproduce a pre-row build bit-for-bit and the mode load itself consumes no RNG), fill (generate_rand_bytes() the owned get_writable_struct(size) allocation so parsers reading byte 0 first see non-residue content), havoc (fill plus a bounded byte-mutation pass capped at BLOB_HAVOC_MAX_OPS -- bit-flip / byte-flip / set-interesting byte+word+dword drawn from get_boundary_value() / get_interesting_value()), or cmpdict (havoc plus a bounded buffer-redqueen pass capped at BLOB_CMPDICT_MAX_INSERTS -- pull a learned cmp constant via cmp_hints_try_get(nr, do32, ...) and splat it into the buffer at a random offset with a random width drawn from {1,2,4,8} bytes, little-endian; pool misses are silent and do not bump blob_dict_inserts. Less reproducible under a fixed seed than fill / havoc -- the cmp-hint pool state depends on values the kernel has handed back at run time.). Every write is clamped inside the get_writable_struct(size) allocation; pure byte content, no pointer-like aliasing." },
	{ "blob-ab-mode",	 0,  "within-run A/B harness for the blob-mutator content-authoring lane (default off, opt-in only): when set, each blob_fill() coin-flips HAVOC vs CMPDICT for that fill so both modes run in one process against the same warm corpus / coverage / kernel state at every moment -- the confound that flattens sequential blob-mode runs (warm-start creep, saturation) cancels.  All blob-side RNG draws for the fill (the coin-flip, havoc arms, cmpdict pulls, and the nested generate_rand_bytes / cmp_hints_try_get) route through a dedicated per-child rnd_blob_state stream via a swap of rnd_state around blob_fill(), keeping the main syscall-selection stream identical to what it would have been without the flag; without this the modes desync the main stream and the comparison leaks (cmpdict pulls more RNG than havoc).  The dispatch-site novelty gate credits blob_ab_<mode>_fills and blob_ab_<mode>_new_edges per call for the stashed mode; the verdict metric is new_edges / fills per mode -- an ~2x separation is a real effect, a null (rates equal) is a solid answer.  When the flag is absent the caller gate and blob_fill() body bypass the ab path entirely and blob mutation is byte-identical to a build without this row." },
	{ "arg-len-semantics",	 0,  "object-size-relative ARG_LEN draw mode (default off): off (gen_arg_len calls get_len() verbatim, no companion-arg lookup, no extra RNG draw -- byte-identical to a build without this flag), or on (when the slot before an ARG_LEN is an ARG_ADDRESS / ARG_NON_NULL_ADDRESS whose value falls in a tracked writable region, draw the length from a size-relative boundary set capped by the region's remaining extent so a kernel-WRITES-buffer syscall cannot scribble past the writable region; falls back to get_len() on no companion / unresolvable size)." },
	{ "bdev",		'b', "Add /dev node to list of block devices to use for destructive tests." },
	{ "canary-seed",	 0,  "comma-separated list of childop names to override the built-in priority canary seed list. Names match alt_op_name (e.g. 'genetlink_fuzzer,bpf_lifecycle'). Unknown names abort startup." },
	{ "canary-slots",	 0,  "reserve N slots from the front of --alt-op-children to run the dormant-op canary queue (default: min(alt-op-children, 2) when unset). Clamped to min(N, alt_op_children); N=0 disables the queue identically to --no-canary-queue." },
	{ "canary-window",	 0,  "invocations of the active canary op per window (default 10000, range 1000..1000000). Counted against the per-op invocation counter, not the fleet-wide op count, so window size is independent of -C and --canary-slots. Lower windows are too noisy to promote on; higher windows let a useless op squat a slot for too long." },
	{ "childop-kcov-attribution", 0, "per-childop KCOV attribution mode: off (no bracketing, childop_edges_clean stays zero; budget multipliers stay at unity and canary windows always demote on zero_edges), dual (default; bracket every eligible alt-op and publish the per-call edge delta to childop_edges_clean -- adapt_budget and the canary queue consume this clean signal, the global-delta path keeps writing childop_edges_discovered as a diagnostic comparator), or on (reserved; identical to dual until the discovered counter is retired)." },
	{ "childop-cmp-harvest", 0, "DEFAULT OFF. Open a per-childop KCOV_TRACE_CMP bracket on CMP-mode children at the child.c childop dispatch gate; childop syscalls routed through trinity_cmp_syscall harvest their CMP operands into the QUARANTINED childop_recent_pools[nr][do32] lane (non-persisted, does NOT evict the durable per-syscall cmp pool). Accepts 'off' (the bracket is never opened; trinity_cmp_syscall is a no-op wrapper around trinity_raw_syscall; every childop_cmp_* shadow counter stays at zero -- the childop dispatch surface is byte-identical to a build without this knob) or 'on' (the bracket opens on every CMP-mode child whose dispatch reaches the existing op_uses_outer_bracket gate; honour the §3.2 all-routed invariant on any childop migrated to trinity_cmp_syscall). Per-childop migration to the wrapper is a separate per-op step earned by the conversion-chain metrics; the OFF default ships the harvest path behaviour-neutral." },
	{ "childop-cmp-consume", 0, "DEFAULT OFF. Enable the SHADOW consume-side resolver childop_cmp_value() at childop field sites (rxrpc pilot: kver / security_index / ticket_length / toklen / tktlen / sec_ix / enctype in childops/net/rxrpc-key-install.c). Accepts 'off' (childop_cmp_value returns the caller's rng fallback verbatim before any cmp_hints_try_get_ex probe; every childop_cmp_consume_* counter in kcov_shm stays at zero and the field-site pick stream is byte-for-byte identical to a build without this knob) or 'on' (the resolver probes the durable per-nr pool via cmp_hints_try_get_ex and bumps _would_pick / _would_miss / _would_value_differs on the outcome, but STILL returns the caller's rng fallback -- no arg is changed and no downstream behaviour differs). Independent of --childop-cmp-harvest: the two knobs gate producer-side and consumer-side of the same childop CMP pool, and the pool is shared, so consume can bump _would_pick against warm-started / non-childop entries even with harvest OFF. The conversion-chain counters (_candidate_accepted / _arg_changed / _outcome_changed / _new_cov) ship declared but never bumped in this build; C3/C4 slices fill them in once the shadow readout justifies live consume." },
	{ "children",		'C', "specify number of child processes" },
	{ "clowntown",		 0,  "enable clowntown mode" },
	{ "cmp-frontier", 0, "CMP-weighted alternate picker arm for the silent regime of set_syscall_nr_coverage_frontier (default off): off (the silent gate skips the arm entirely -- no mode-load past the early return, no CMP-counter load, no plateau-hint load, no weight change; fixed-seed runs reproduce a pre-row build bit-for-bit and the mode load itself consumes no RNG), shadow-only (compute the CMP-weighted alternate weight from kcov_shm->per_syscall_cmp_inserts[nr] + kcov_shm->childop_cmp_pool_inserts[nr] (insert-volume base) plus a conversion-rate bonus from per_syscall_cmp_injected vs per_syscall_cmp_hint_pc_wins + per_syscall_cmp_hint_transition_wins (gated on CMP_FRONTIER_MIN_INJECTED so 1/1 noise does not dominate; 0%-converters degrade to the historical inserts-only signal), via ilog2 clamps + the CMP_FRONTIER_SIGNAL_SCALE multiplier saturated at FRONTIER_COLD_SCALE, sample the plateau classifier, and bump the cmp_frontier_samples + would_route shadow counters in stats so the would-be route volume is measurable, but leave the live silent-regime weight at the PC-led value -- picks identical to OFF for a given seed), or combined (the live silent-regime weight is REPLACED with the CMP-weighted weight on picks where the plateau classifier reads PLATEAU_HYPOTHESIS_CMP_RISING_PC_FLAT, the 'rank the silent regime by CMP-derived signal instead' contract; off-plateau picks retain the PC-led weight, and the (w+1)/(SCALE+1) accept floor keeps a zero-CMP-signal syscall reachable rather than unreachable under the swap; the cmp_frontier_live_routes counter records the gated route volume).  Degrade-safe: kcov_shm-less / out-of-range short-circuits cmp_frontier_weight() to 0 before any CMP counter is touched, matching the FRONTIER_COLD_SCALE fallback the rest of the picker file takes." },
	{ "cmsg-richness", 0, "extended sendmsg/sendmmsg control-message generator (default off): off (pick_cmsg_kind() draws from the original 5 base kinds with a single rnd_modulo_u32 call; the cmsg-build site is bit-for-bit identical to a build without this lever -- no extra RNG draws, no new kinds, no new arms), or on (extends the per-call cmsg pool with family-gated single-cmsg kinds -- IP_PKTINFO / IPV6_PKTINFO, IP_TOS / IP_TTL / IP_RETOPTS, IPV6_TCLASS / IPV6_HOPLIMIT / IPV6_RTHDR, SCM_TXTIME, TLS_SET_RECORD_TYPE -- and adds a ONE_IN(4) multi-cmsg packer that sizes the buffer by the sum of CMSG_SPACE(plen) across 2-3 distinct entries from a per-family pool, zero-fills the buffer up front, and walks CMSG_FIRSTHDR -> CMSG_NXTHDR with CMSG_LEN(plen) per entry)." },
	{ "corpus-save-errno-grad-live", 0, "DEFAULT OFF. Enable the errno-gradient corpus save trigger (CORPUS_SAVE_REASON_ERRNO): when a syscall returns a non-EFAULT errno bucket for the first time this run, admit its args to the per-syscall ring. Flag off keeps the corpus admission distribution byte-identical to a build without this trigger; the errno_grad_save_would_save shadow counter is bumped regardless of this flag so the would-be-save volume is measurable before flipping live." },
	{ "context-pool", 0, "Path-A regular_suppressed context-axis shadow observer for the HEURISTIC and RANDOM picker arms in random-syscall.c (default off): off (skip the classifier entirely, byte-identical to today; no kcov_shm access, no per-syscall counter loads, no spare-lane evaluation, no context_regular_suppressed_* counter bump; fixed-seed --dry-run pick streams are bit-for-bit identical to a build before this row), shadow-only (at pick-finalise, alongside the sibling cost_pool_selector_live_note attribution, classify the accepted syscall as regular_suppressed when its run-persistent kcov counters say it is regular-dead -- lifetime per_syscall_calls_total >= CONTEXT_REGULAR_SUPPRESSED_CMIN AND per_syscall_errno[SUCCESS] == 0 AND per_syscall_edges_total == 0 AND per_syscall_errno[EPERM] / calls >= CONTEXT_REGULAR_SUPPRESSED_EPERM_PCT -- and bump the context_regular_suppressed_* shadow counters split by the shared frontier_spare_lane_decide spare cascade (windowed-edges / arggen / objproducer / none-of-the-above == would_skip); selection stays byte-identical -- no goto-retry or accept-gate is influenced by the classifier, no live regular-pool deactivation fires), or combined (RESERVED: the enum value exists for a future commit that wires the live regular-pool removal (deactivate_syscall_locked on the regular_suppressed subset) so a follow-up can land without renumbering the enum; THIS BUILD treats combined identically to shadow-only -- classifier evaluates and counters bump, no live pool change happens).  Validate the per-syscall would_skip distribution against the measured EPERM hogs (fchown / chown / lchown / fchownat + the cred family as seen at uid 1026) (expected high) and against syscalls with unprivileged regular value (expected ~0) under shadow-only before tuning CMIN / EPERM_PCT or wiring the COMBINED live suppression. See include/strategy.h enum context_pool_mode for the mode contract and CONTEXT_REGULAR_SUPPRESSED_CMIN / CONTEXT_REGULAR_SUPPRESSED_EPERM_PCT for the classifier thresholds." },
	{ "cost-pool-selector", 0, "cost-pool one-shot selector mode for the HEURISTIC and RANDOM picker arms in random-syscall.c (default off): off (skip the observer entirely, byte-identical to today; no per-pool counter loads, no divide, no cost_pool_selector_shadow_* counter bump), shadow-only (at the top of each pick, after choose_syscall_table but before the retry loop's live rnd_modulo_u32 draw, read the arch-specific nr_active_cheap / nr_active_exp pair under RELAXED, compute the closed-form per-pool expected fractions from the section 4.1 identity (p_exp = n_exp / (n_cheap*R + n_exp) with R = EXPENSIVE_ADAPTIVE_FLOOR = 1000), and accumulate them into the cost_pool_selector_shadow_picks / cost_pool_selector_shadow_expensive_ppm_sum aggregate; NO shadow pick is drawn -- the observer consumes ZERO rnd_u32() calls so the pick stream stays identical to off for a given seed; the parallel cost_pool_selector_live_cheap_picks / cost_pool_selector_live_expensive_picks accepted-pick counters bump regardless of this flag so the analytical (shadow) fraction can be validated empirically against the live draw-then-reject fraction on any run), or combined (RESERVED: the enum value exists for a future commit that wires the live coin-then-draw dispatch on top of the shm->active_cheap*[] / active_expensive*[] pools; THIS BUILD treats combined identically to shadow-only -- observer accumulates, live pick stays flat draw-then-reject).  Validate (shadow_expensive_ppm_sum / (shadow_picks * 1e6)) matches (live_expensive_picks / (live_expensive_picks + live_cheap_picks)) under shadow-only before wiring COMBINED." },
	{ "cmp-cfactual", 0, "SHADOW counterfactual-attribution rollout mode for the cmp-hint pool (default off): off (skip the cfactual capture + control-replay entirely, byte-identical to today; no shm access, no per-child state read, no RNG consumption, no extra syscall runs; a fixed-seed --dry-run pick + syscall stream is byte-for-byte identical to a pre-row build), or shadow (on every credit_pc(win) drain, walk the per-child cmp-hint consume stash and for each captured candidate re-dispatch the same syscall with fresh args EXCEPT the hint slot pinned to a control value that fails the compare at cmp_ip; classify inner_new_edges == false as cmp_hint_cfactual_win (the causal true-positive count), inner_new_edges == true as cmp_hint_cfactual_coincidence (the correlational-counter miscredit lane), and replay-gate failures as cmp_hint_cfactual_flaky; served_from_shared candidates route to cmp_hint_cfactual_shared_quarantined and skip the replay entirely, mirroring the credit-drain's shared-tier quarantine).  No live injection / eviction / ranking path reads cmp_cfactual_mode or any of the four cfactual counters under either mode -- live pool selection is byte-identical either way.  Shares the redqueen per-window replay cap (REDQUEEN_REEXEC_WINDOW_CAP) so cfactual and redqueen replays cannot each burn their own cap and pin the child on replay work.  The Phase-2 shadow-to-live promotion / retirement decision on the measured cfactual win / (win + coincidence) causal conversion rate is a separate row." },
	{ "cmp-shared-tier", 0, "fleet-wide shared cmp_ip tier rollout mode (default off): off (both the collect-side insert and the get-side shadow probe short-circuit BEFORE any shared-tier shm access; every cmp_shared_tier_* counter stays at zero, and a fixed-seed --dry-run pick stream is bit-for-bit identical to a build before the shared tier landed), shadow (populate the tier at warm-load and on every fresh pool_add_locked success, and on every cmp_hints_try_get_ex cold-miss return -- durable per-nr pool empty on the requested (nr, do32) and the recent-tier pre-pass did not serve -- bump cmp_shared_tier_shadow_warmstart_eligible when the tier has at least one non-entry-path IP available to seed from; the probe does NOT read or return a tier value, does NOT consume RNG, and does NOT change what try_get returns; the entry-path filter (distinct_nr_count > CMP_SHARED_TIER_ENTRY_PATH_NR_MAX) excludes IPs that fire under too many syscalls to be a useful warm-start seed, and cmp_shared_tier_shadow_dedup_supplied captures the cross-nr redundant-learn opportunity size), or combined (RESERVED: the enum value exists for a future commit that wires the live warm-start seed served from a non-entry-path shared-tier value; THIS BUILD treats combined identically to shadow -- tier populated, observer accumulates, live pick stays byte-for-byte unchanged).  Validate the (shadow_dedup_supplied / cmp_hints_unique_inserts) cross-nr redundancy rate and the (shadow_warmstart_eligible / cold-miss population) opportunity size under shadow before wiring COMBINED." },
	{ "cred-throttle",	 0,  "DEFAULT OFF. Enable the credential-syscall throttle: when a credential class (setregid/setreuid/setresuid/setresgid/setgid/setuid/setfsuid/setfsgid/setgroups) has accumulated >=64 attempts with zero successes and EPERM+EINVAL dominating >=90% of returns, downweight the class by rejecting 31/32 of subsequent picks. Flag off keeps the picker distribution byte-identical to a build without this row; the per-class observability counters are bumped regardless of this flag." },
	{ "frontier-live-cooldown-mode", 0, "LIVE-regime cooldown discriminator mode for the coverage-frontier picker's LIVE-regime miss-attribution path (default off): off (skip the discriminator entirely, byte-identical to today; selection AND the new frontier_live_cool_* shadow counters both stay zero), shadow-only (compute the spare-lane discriminator -- windowed-edges + distinct-CMP / first-success / ret_objtype lanes, gated by the FRONTIER_LIVE_COOL_CMIN low live floor -- inside the existing streak >= FRONTIER_LIVE_MISS_COOLDOWN branch and bump frontier_live_cool_* shadow counters; selection stays byte-identical -- the existing frontier_live_would_skip projection keeps bumping unchanged so the (live_cool_would_skip / live_would_skip) ratio reads the over-cool the discriminator would remove), or combined (RESERVED: the enum value exists for a future commit that wires the live divergence -- rotation-loop halving + per-syscall reject -- gated on the discriminator; THIS BUILD treats combined identically to shadow-only). Validate the per-syscall would-skip distribution against gettid / sched_get_priority_max (expected high) and bpf / io_uring_setup / openat / io_setup / futex / setxattrat (expected ~0) under shadow-only before tuning C_min or wiring the COMBINED divergence. Independent of the existing boolean --frontier-live-cooldown (which gates the rotation-loop halving)." },
	{ "frontier-barren-demote", 0, "floored-barren sub-floor demote predicate mode for the coverage-frontier picker's silent-regime accept site (default-off; only for a targeted debugging run): off (skip the barren predicate entirely, byte-identical to today; selection AND shadow counters both stay zero), shadow-only (evaluate the vetted floored-barren predicate -- num_args == 0 AND ret_objtype == OBJ_NONE AND sanitise == NULL AND reach <= FRONTIER_BARREN_MAX_REACH AND calls > FRONTIER_BARREN_C_MIN AND lifetime edges == 0 AND windowed edges == 0 -- inside the silent-regime accept block and bump the frontier_barren_* shadow counters; selection stays byte-identical -- no goto-retry is gated on the predicate), or combined (RESERVED: the enum value exists for a future commit that wires the live sub-floor divergence swapping the silent-branch accept denominator to (FRONTIER_COLD_SCALE * FRONTIER_BARREN_DEMOTE_MULT + 1); THIS BUILD treats combined identically to shadow-only -- predicate evaluates and counters bump, no live divergence fires). Measure-only shadow arm: the vetted skeleton (no producer, no mutator, low reach) is what keeps object-producers, state-mutators, and heuristic-arm spike sources out of the demote set -- num_args == 0 alone is necessary but NOT sufficient. Validate the per-syscall would-skip distribution reads the pure zero-arg getter cohort before considering the combined ramp." },
	{ "frontier-saturation-cooldown", 0, "saturation-cooldown predicate mode for the coverage-frontier picker's silent-regime accept site (default off): off (skip the satcool predicate entirely, byte-identical to today; selection AND shadow counters both stay zero), shadow-only (compute the corrected windowed-edge plateau + FRONTIER_SATCOOL_CMIN magnitude + distinct-CMP / first-success / ret_objtype spare-lane predicate inside the silent-regime accept block and bump frontier_satcool_* shadow counters; selection stays byte-identical -- no goto-retry is gated on the predicate), or combined (RESERVED: the enum value exists for a future commit that wires the live reject; THIS BUILD treats combined identically to shadow-only -- predicate evaluates and counters bump, no live reject fires). Validate the per-syscall would-skip distribution against syncfs / sendfile / semget / writev (expected high) and removexattrat / futex / io_uring_setup / bpf (expected ~0) under shadow-only before tuning C_min or wiring the COMBINED reject." },
	{ "frontier-group-antilock", 0, "group-bias anti-lock-in damper mode for the heuristic-arm picker's group_bias gate (default off): off (skip the windowed-pin predicate entirely, byte-identical to today; per-child streak / watermark / fd-warm bookkeeping AND shadow counters all stay dormant), shadow-only (run the dispatch-step per-child bookkeeping and compute the pin_stale && !pin_warm release predicate at the group_bias gate site, bumping frontier_frseq_* shadow counters; selection stays byte-identical -- no group-bias gate is skipped on the predicate), or combined (RESERVED: the enum value exists for a future commit that wires the live pin release; THIS BUILD treats combined identically to shadow-only -- predicate evaluates and counters bump, no live release fires). Validate the per-syscall would-skip distribution against rseq_slice_yield / getpgrp / sched_yield (expected high) and socket / sendto / openat (expected ~0) and the per-group distribution against GROUP_PROCESS (=5, expected high) vs GROUP_NET / GROUP_VFS (expected ~0) under shadow-only before tuning MIN_STREAK / COV_WINDOW or wiring the COMBINED release.  No-op unless --group-bias is also set; mirrors the F-RSEQ-5 caveat in the design note." },
	{ "dangerous",		'd', "enable dangerous mode" },
	{ "debug",		'D', "enable debug" },
	{ "disable-fds",	 0,  NULL },	/* handled separately */
	{ "guard-shared",	 0,  "guard shared mmap regions with PROT_NONE guard pages to catch out-of-bounds writes (needs a GUARD_SHARED=1 build; otherwise accepted but warns to rebuild): off, pools (focused scope -- kcov_shm, shared str/obj heap, childdata; default when given bare), or all (every alloc_shared region -- may need a vm.max_map_count bump to avoid mprotect-split ENOMEM)." },
	{ "domain",		'P', "specify specific network domain for sockets" },
	{ "dry-run",		 0,  "run arg-gen + sanitise but skip the syscall (safe ASAN/repro mode)" },
	{ "enable-fds",		 0,  NULL },	/* handled separately */
	{ "epoch-iterations",	 0,  "syscalls per epoch before restarting (must be > 0; omit to disable)" },
	{ "epoch-timeout",	 0,  "seconds per epoch before restarting (must be > 0; omit to disable)" },
	{ "exclude",		'x', "exclude syscall(s): name or comma-list, each optionally @32 or @64" },
	{ "explorer-children",	 0,  "reserve N children to always run STRATEGY_RANDOM as a strategy-independent explorer pool (default: max_children/4 under --strategy=bandit, 0 otherwise; max: max_children/2). Works in any picker mode; non-bandit modes get no explorer pool unless this is set." },
	{ "fork-pressure-drain", 0, "opt-in: under sustained fork() failure (>=100 consecutive spawn_child failures), suppress canary picks of pid-heavy ops (pidfd_storm, qrtr_bind_race, pfkey_spd_walk, l2tp_ifname_race, statmount_idmap_overflow, sysfs_string_race) for 30 s so the canary picker stops piling new fork demand on a parent already losing the spawn race. fork_storm is always skipped via the risky-defer set. Default off." },
	{ "group",		'g', "only run syscalls from a certain group (vfs,vm,net,ipc,process,signal,io_uring,bpf,sched,time,xattr)" },
	{ "group-bias",		 0,  "bias syscall selection toward the same group as the previous call" },
	{ "help",		'h', "show this help" },
	{ "ioctls",		'I', "list all ioctls" },
	{ "kcov-trace-size", 0, "per-child KCOV PC-trace buffer size in number of unsigned longs (default: KCOV_TRACE_SIZE = 262144 longs = 2 MB on 64-bit). Must be a power of 2 in [KCOV_TRACE_SIZE, KCOV_TRACE_SIZE_MAX] (max 4M longs = 32 MB). A/B knob for testing whether the hot syscalls (mincore/mlock/writev/shmget/shmat) that today saturate trace_buf[0] at KCOV_TRACE_SIZE-1 are dropping real tail edges; default value is byte-identical to a build without this flag." },
	{ "frontier-noise-sample", 0, "SHADOW-ONLY per-syscall clean-vs-noisy attribution sampler (default 0 = off).  When N > 0, every Nth per-syscall enable/disable bracket in dispatch/syscall.c snapshots the shared edges_found counter before enable and after disable, records the delta into kcov_shm->per_syscall_edges_noisy[nr], and bumps per_syscall_noisy_samples[nr] so a reader can scale the sampled sum back up by N to estimate the full-population global-delta denominator.  Paired with the pre-existing per_syscall_edges[] clean numerator and the per_syscall_edges_clean_remote[] remote-context split (bumped inside kcov_collect's found_new branch when kc->remote_mode), this feeds the per-syscall attribution-confidence diagnostic block in the stats dump.  SHADOW-ONLY: no live picker, accept-gate, or scoring code reads any of the three counters -- selection stays byte-identical to a build with N=0.  With N=0 the sampler helpers short-circuit at the earliest gate and issue zero edges_found loads on the syscall hot path, so the default build carries zero added cost.  Suggested first fleet value 64 (loads ~1.5% of the time, statistically usable denominator over a run since each syscall fires thousands of times).  Cadence is a single non-atomic per-child increment on file-scope state in dispatch/syscall.c; no cross-child shared counter is touched for the cadence itself." },
	{ "kcov-transition-coverage", 0, "shadow transition-coverage map mode: shadow (default; hash consecutive canonical PCs into a separate 16M-slot map and surface a transition top-N beside the PC top-N in the stats dump, with no effect on reward/frontier/plateau steering) or off (skip the per-PC transition hash entirely)." },
	{ "kcov-transition-reward", 0, "transition-edge reward mode (requires --kcov-transition-coverage=shadow): combined (default; feed the capped transition delta into frontier_cold_weight, bandit_record_pull, and the frontier-edge ring so syscalls producing only transitions earn frontier credit), shadow-only (compute the transition reward and bump per-strategy attribution counters in shm->stats but leave live picker behaviour byte-identical to the pre-knob baseline -- rollback path), or off (skip the reward path entirely). Remote-mode transitions are excluded from live reward under combined until ordering quality is checked." },
	{ "bandit-reward-edge-count", 0, "blended edge-count secondary reward for the UCB1 bandit (default off): off (byte-identical to the pre-knob baseline -- edge_count_term is not computed, no shadow counter bumps, and bandit_reward_calls[] stays call-count + weighted CMP-novelty + trans_term), shadow-only (compute edge_count_term = pc_edge_count / EDGE_COUNT_BANDIT_REWARD_WEIGHT_RECIPROCAL and bump the bandit_edge_count_reward_added counter on every non-forced window where the term is non-zero, but do NOT fold the term into the ucb1 total -- selection stays byte-identical to off, the counter surfaces how often COMBINED would move the reward), or combined (fold edge_count_term into the reward total so the bandit learns from real bucket-edge yield alongside the call-count headline). SR_PLATEAU_FORCE windows are excluded from the learner path even under combined, mirroring the CMP and transition secondary reward terms. Shadow-first ramp -- validate the shadow firing rate on a real run before promoting the mode." },
	{ "expensive-adaptive", 0, "adaptive accept-rate mode for the EXPENSIVE early-out gate in random-syscall.c (default off): off (the gate is byte-identical to the prior `syscall_is_expensive && !ONE_IN(1000)` expression -- no kcov_shm reads, no adaptive math, single ONE_IN(1000) RNG draw fires only on EXPENSIVE-flagged candidates so the pick stream is preserved bit-for-bit for a given seed), shadow-only (compute the adaptive denominator from per-syscall productivity (per_syscall_edges + warm-loaded _prior) / per_syscall_calls with a total_calls -- last_edge_at gap decay back toward the floor, but the LIVE accept still draws ONE_IN(1000) so the pick stream stays identical to off; placeholder for the follow-up row that wires shadow A/B counters), or combined (the adaptive denominator drives the live accept -- a productive EXPENSIVE syscall earns up to a 1/50 rate, a once-productive-now-stale slot decays back to the 1/1000 floor over EXPENSIVE_ADAPTIVE_DECAY_STEPS contiguous KCOV_COLD_THRESHOLD-sized gap steps). Degrade-safe: kcov-less / bad-index callers fall back to the static 1/1000 floor." },
	{ "kernel_taint",	'T', "controls which kernel taint flags should be considered (see README)" },
	{ "list",		'L', "list all syscalls known on this architecture" },
	{ "max-runtime",	 0,  "maximum runtime before exit, with optional suffix s/m/h/d (e.g., 30s, 10m, 2h, 1d). Overrides --epoch-timeout." },
	{ "memory-high",	 0,  "children/memory.high back-pressure threshold (workers cgroup). Accepts \"max\", N% of MemTotal, or N[KMG] bytes. Default: 50%." },
	{ "memory-max",		 0,  "total trinity memory budget. Split into children/memory.max=<this>-parent_high and a small parent reservation parent_high=min(200M,this/16) so worker OOM doesn't take the parent. Accepts \"max\", N% of MemTotal, or N[KMG] bytes. Default: 60%." },
	{ "memory-swap-max",	 0,  "children/memory.swap.max cap (workers cgroup). Accepts \"max\", N% of MemTotal, or N[KMG] bytes. Default: 20%." },
	{ "no-canary-queue",	 0,  "disable the dormant-childop canary queue entirely; the dormant gate is consulted as a static compile-time vector and no canary slots are reserved." },
	{ "no-cgroup",		 0,  "skip self-cgroup creation entirely (no in-binary memory containment)" },
	{ "no-chain-warm-start", 0, "skip loading and saving the persisted sequence chain corpus" },
	{ "chain-resource-typing", 0, "bias chain generation to pair resource producers with consumers using the small fd-family table in sequence.c (default off): off (byte-identical to today; classify hook returns early), shadow (count per-kind chain_restype_produced / chain_restype_would_bias but leave generation identical to off -- pure observation to measure the opportunity), or live (actually override the next chain link with a random consumer of the produced kind, probabilistically so other links stay possible; bumps chain_restype_biased). Per-kind chain_restype_save / chain_restype_replay_win are the productivity signals that decide which families to extend into." },
	{ "no-cmp-hints-warm-start", 0, "skip loading and saving the persisted kcov CMP-hint pool" },
	{ "no-kcov-warm-start",	 0,  "skip loading and saving the persisted kcov edge bitmap" },
	{ "no-startup-isolation", 0,  "skip the parent-side unshare(CLONE_NEWNET|CLONE_NEWNS) + MS_PRIVATE remount that the root-launched fuzzer does in init_pre_fork() (children then take the per-child unshare path). Default off; non-root runs never attempt parent-side isolation regardless." },
	{ "no-warm-start",	 0,  "skip loading and saving the persisted minicorpus" },
	{ "no_domain",		'E', "specify network domains to be excluded from testing" },
	{ "print-disabled-syscalls", 0, "print syscalls disabled via AVOID_SYSCALL or NEED_ALARM and exit" },
	{ "quiet",		'q', "suppress the per-second progress line (other output unchanged)" },
	{ "self-corrupt-canary", 0, "DEFAULT OFF.  Deeper self-corruption detector companion to the always-on gate loggers in kcov / mm / dispatch.  At every dispatch, checksum a bounded signature of the child's critical self-state (child->local_stats, child->objects, child->kcov.trace_buf/cmp_trace_buf/dedup pointers, and a 64-byte trinity-heap sentinel filled with SELF_CORRUPT_CANARY_MAGIC) before do_syscall; recompute after; on mismatch log_self_corrupt_culprit names the syscall whose dispatch clobbered the state, catching mid-struct scribbles (glibc-heap family aborts, wrong-offset writes) that leave the tracked-pointer VA bands intact and slip past the always-on gates.  OFF short-circuits before any signature computation and before the sentinel is allocated at init_child, so a fixed-seed --dry-run stderr md5 stays byte-identical to a build without this row." },
	{ "random",		'r', "pick N syscalls at random and just fuzz those" },
	{ "reach-band", 0, "reach-banded silent-regime weight adjustment for the coverage-frontier picker's frontier_cold_weight() consumer (default off): off (skip the band classification entirely, byte-identical to today; no extra per_syscall_edges_prior / total_calls / last_edge_at loads, no demote/boost arithmetic, no weight change -- fixed-seed runs reproduce a pre-row build bit-for-bit), shadow-only (compute the LOW / MID / HIGH band classification and the would-demote / would-boost decision inside frontier_cold_weight but leave the returned weight unchanged; placeholder for a follow-up that adds per-band shadow counters), or combined (the band adjustment is applied to the live silent-regime weight -- a MID-reach stale slot has its weight halved on top of the cold-skip path's existing demote, a HIGH-reach fresh slot has a quarter of the FRONTIER_COLD_SCALE headroom lifted back onto its weight so the inverse-productivity transform does not starve the long-tail deep-reach discoverer).  Degrade-safe: frontier_cold_weight's kcov-less / out-of-range short-circuit fires before the band hook, matching the FRONTIER_COLD_SCALE fallback the rest of the picker file takes." },
	{ "redqueen-pending-pick", 0, "Retained for compatibility; no-op.  The RedQueen re-exec consumer at the dispatch_step tail now drains every staged reexec_pending[] entry per parent dispatch, so the 'random' vs 'first' selection no longer alters behaviour.  Still parsed (accepts 'random' or 'first') so existing invocations do not break; per-pending-index success counters (kcov_shm->reexec_pending_pick_success[]) are still bumped at each entry's true index inside redqueen_reexec_step(), so per-slot / per-index re-exec lift remains directly readable." },
	{ "show-unannotated",	 0,  "show unannotated syscalls" },
	{ "stats",		 0,  "show errno distribution per syscall before exiting; also writes a per-window stats-timeseries-<epoch>.jsonl in the launch CWD on every print_stats() tick.  Head is {\"t\":op_count,\"edges_total\":N,\"edges_gained_this_window\":D,...} followed by causal columns (edges_found_total + gained; edges_warm_loaded / distinct_edges_warm_loaded and edges_run_gained / edges_found_run_gained; trace_truncated + cmp_trace_truncated levels + deltas; cmp_hints_injected / consumed / cmp_hint_wins / cmp_hyp_live_injected / cmp_hyp_consumed levels + deltas; plateau_hypothesis + plateau_intervention_mode names; by_strategy array with per-arm pulls/reward_calls/reward_pc_edges + deltas; by_childop array with per-op edges_discovered / edges_clean / calls_with_edges / invocations / would_promote / would_demote levels + deltas plus canary_active / canary_promoted flags, so a window's edge jump is attributable to an alt-op even when per-syscall deltas are zero) and a per_syscall array of {\"nr\":N,\"edges\":E,\"edges_gained\":D,\"kcov_calls\":K,\"attempted_calls\":A,\"local_edges\":L,\"local_edges_gained\":LG,\"remote_edges\":R,\"remote_edges_gained\":RG,\"cmp_injected\":CI,\"cmp_injected_gained\":CIG,\"cmp_hint_pc_wins\":CW,\"cmp_hint_pc_wins_gained\":CWG}.  Cumulative levels are kept alongside every _delta / _gained field (first window's delta = the level) so plateaus and single-window bursts are legible without differencing consecutive lines" },
	{ "stats-json",		 0,  "emit dump_stats output as a single JSON object on stdout (machine-readable)" },
	{ "stats-log-file",	 0,  "path to append periodic stats dumps to (in addition to stdout)" },
	{ "strategy",		 0,  "arm-selection POLICY for the multi-strategy rotation (NOT a specific arm): bandit/ucb1 (default) or round-robin/rr. The set of arms is fixed (heuristic, random, coverage-frontier); this flag picks how the rotation chooses between them." },
	{ "syslog",		'S', "log important info to syslog (useful if syslog is remote)" },
	{ "verbose",		'v', "increase output verbosity. Repeat for more detail (-vv)" },
	{ "victims",		'V', "path to victim files (may be repeated)" },
	{ "warm-start-path",	 0,  "override the on-disk minicorpus path (default: $XDG_CACHE_HOME/trinity/corpus/<arch>)" },
	{ "writer-pin-sweep",	 0,  "DEFAULT OFF. Heavyweight debug tool -- only enable for a targeted corruption hunt. Stage-1 detector for the writer-pinning canary: at every post-syscall validate phase, sweep the shared minicorpus rings for a stomped wp_canary or count>32 invariant violation. On the first hit, emit one SUSPECT line naming the observer context (NOT the wild writer) and the stomped address. The address is the deliverable for the Stage-2 --writer-watch=<addr>, which IS the synchronous writer-namer. Default-off path is byte-identical (one branch-predicted if test)." },
	{ "writer-pin-stride",	 0,  "DEFAULT 1. Throughput escape hatch for --writer-pin-sweep: only sweep every Nth post-syscall validate phase. Default 1 = sweep every syscall, which keeps the writer-attribution window at one op. Values >1 widen the window past one op and degrade the sweep to 'some recent writer' -- documented escape hatch only; the writer-namer is Stage-2 --writer-watch, not the sweep." },
	{ "writer-watch",	 0,  "DEFAULT OFF. Heavyweight debug tool -- only enable for a targeted corruption hunt. Stage-2 writer-namer for the writer-pinning canary: arm a perf_event_open hardware WRITE breakpoint (PERF_TYPE_BREAKPOINT, HW_BREAKPOINT_W, bp_len=8, exclude_kernel=0) on the given 8-byte address per-child after fork. A write to that address traps synchronously in the writing child at the exact instruction; the SIGTRAP handler dumps writer_pc (raw, resolve offline against [load-bases]), syscall nr, childop name, op_nr, pid -- the exact WILD WRITER, with no race. Up to 4 watchpoints are supported by hardware; this code arms ONE. Argument is a hex address (with or without 0x prefix), typically the bad_addr surfaced by a prior --writer-pin-sweep run." },
	{ NULL,			 0,  NULL },
};

/* Short-only options that don't appear in longopts. */
static const struct option_help shortonly_descs[] = {
	{ NULL, 'c', "target specific syscall(s): name or comma-list, each optionally @32 or @64" },
	{ NULL, 'N', "do N syscalls then exit" },
	{ NULL, 's', "use N as random seed" },
	{ NULL,  0,  NULL },
};

void usage(void)
{
	const struct option_help *h;

	outputerr("%s\n", progname);

	for (h = option_descs; h->name != NULL; h++) {
		if (h->desc == NULL)
			continue;

		if (h->shortopt)
			outputerr(" --%s, -%c: %s\n", h->name, h->shortopt, h->desc);
		else
			outputerr(" --%s: %s\n", h->name, h->desc);
	}

	enable_disable_fd_usage();

	for (h = shortonly_descs; h->shortopt != 0; h++)
		outputerr(" -%c: %s\n", h->shortopt, h->desc);

	outputerr("\n");
	exit(EXIT_SUCCESS);
}
