/*
 * net/netlink/rtnl-ack-oracle.c
 *
 * Per-nlmsg_type ACK oracle for the generic NETLINK_ROUTE send path.
 *
 * The main fuzzer issues sendmsg() for every generated rtnl message but
 * never reads the reply.  The counter netlink_nested_attrs_emitted
 * increments on every send -- a coverage signal that looks identical
 * whether the kernel accepted or silently discarded the message.
 *
 * This oracle closes that gap: for each single-message NETLINK_ROUTE
 * packet generated by netlink_gen_msg(), it opens a private socket,
 * sends a copy with NLM_F_ACK forced, drains the NLMSG_ERROR reply, and
 * classifies the kernel's verdict into the per-outcome histogram in
 * shm->stats.rtnl_ack_oracle.  The per-RTM-group accepted counter
 * (type_accepted_per_group[]) records which RTM families the kernel
 * actually processed vs. rejected.
 *
 * Cost note: opening a socket, sending one message, and reading the ACK
 * adds roughly 10-30 us of kernel round-trip overhead per rtnl message
 * on the hot fuzz path.  The full-ACK mode implemented here is the
 * simplest correct baseline.  If run-time measurement shows unacceptable
 * throughput regression, add 1-in-N sampling (keep the socket open across
 * N calls; only call into the oracle on count % N == 0) and document the
 * N chosen at that point.  Do not do that pre-emptively: premature
 * sampling trades accuracy for unverified throughput savings.
 */
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <unistd.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include "shm.h"
#include "rtnl-ack-oracle.h"

/*
 * rtnl_ack_oracle_probe - send one rtnl message on a private socket and
 * record the kernel's ACK verdict in shm->stats.rtnl_ack_oracle.
 *
 * @nlmsg_type: the RTM_* type of the first nlmsghdr in msg_buf; used to
 *   index the per-RTM-group accepted counter.
 * @msg_buf:    the generated message buffer (may be a multi-TLV packet).
 * @msg_len:    length of msg_buf in bytes.
 *
 * The function forces NLM_F_REQUEST|NLM_F_ACK on the first nlmsghdr in its
 * copy, so the kernel always generates an NLMSG_ERROR reply regardless of
 * the flags chosen by gen_nlmsg_flags() for the main fuzz path.
 *
 * A SO_RCVTIMEO of 150 ms is set so recv() returns promptly on kernels
 * that do not reply (e.g. message type is unknown and the kernel silently
 * drops it without an error).  Those cases land in the no_reply bucket.
 */
void rtnl_ack_oracle_probe(unsigned short nlmsg_type,
			   const void *msg_buf, size_t msg_len)
{
	unsigned char rbuf[256];
	struct sockaddr_nl sa;
	struct timeval tv;
	unsigned char *probe;
	struct nlmsghdr *nlh;
	struct nlmsgerr *err;
	ssize_t n;
	int fd, grp, e;

	if (msg_len < NLMSG_HDRLEN || msg_len > 8192)
		return;

	probe = malloc(msg_len);
	if (!probe)
		goto out_sendfail;
	memcpy(probe, msg_buf, msg_len);

	/*
	 * Force NLM_F_REQUEST|NLM_F_ACK on the probe copy.  The original
	 * buffer (used by the main fuzz sendmsg path) is left unchanged.
	 */
	((struct nlmsghdr *)probe)->nlmsg_flags |=
		(unsigned short)(NLM_F_REQUEST | NLM_F_ACK);

	fd = socket(AF_NETLINK, SOCK_RAW | SOCK_CLOEXEC, NETLINK_ROUTE);
	if (fd < 0) {
		free(probe);
		goto out_sendfail;
	}

	tv.tv_sec  = 0;
	tv.tv_usec = 150000; /* 150 ms */
	(void)setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

	memset(&sa, 0, sizeof(sa));
	sa.nl_family = AF_NETLINK;
	if (bind(fd, (struct sockaddr *)&sa, sizeof(sa)) < 0) {
		close(fd);
		free(probe);
		goto out_sendfail;
	}

	n = send(fd, probe, msg_len, 0);
	free(probe);
	if (n < 0) {
		close(fd);
		goto out_sendfail;
	}

	n = recv(fd, rbuf, sizeof(rbuf), 0);
	close(fd);

	if (n < (ssize_t)NLMSG_HDRLEN)
		goto out_noreply;

	nlh = (struct nlmsghdr *)rbuf;
	if (nlh->nlmsg_type != NLMSG_ERROR)
		goto out_noreply;
	if ((size_t)n < NLMSG_HDRLEN + sizeof(struct nlmsgerr))
		goto out_noreply;

	err = (struct nlmsgerr *)NLMSG_DATA(nlh);
	e   = err->error; /* 0 on success, negated errno on failure */

	/*
	 * RTM group index: (nlmsg_type - RTM_BASE) / 4.
	 * Clamped to [-1, MAX_GROUPS); -1 means out of the RTM range
	 * (e.g. a chaos-mode random type < RTM_BASE).
	 */
	grp = ((int)(unsigned short)nlmsg_type - RTM_BASE) / 4;
	if (grp < 0 || grp >= RTNL_ACK_ORACLE_MAX_GROUPS)
		grp = -1;

	if (e == 0) {
		__atomic_add_fetch(&shm->stats.rtnl_ack_oracle.accepted,
				   1, __ATOMIC_RELAXED);
		__atomic_add_fetch(&shm->stats.netlink_nested_attrs_accepted,
				   1, __ATOMIC_RELAXED);
		if (grp >= 0)
			__atomic_add_fetch(
				&shm->stats.rtnl_ack_oracle
				 .type_accepted_per_group[grp],
				1, __ATOMIC_RELAXED);
	} else if (e == -EINVAL) {
		__atomic_add_fetch(&shm->stats.rtnl_ack_oracle.einval,
				   1, __ATOMIC_RELAXED);
	} else if (e == -ERANGE) {
		__atomic_add_fetch(&shm->stats.rtnl_ack_oracle.erange,
				   1, __ATOMIC_RELAXED);
	} else if (e == -EOPNOTSUPP) {
		__atomic_add_fetch(&shm->stats.rtnl_ack_oracle.eopnotsupp,
				   1, __ATOMIC_RELAXED);
	} else if (e == -EPERM) {
		__atomic_add_fetch(&shm->stats.rtnl_ack_oracle.eperm,
				   1, __ATOMIC_RELAXED);
	} else {
		__atomic_add_fetch(&shm->stats.rtnl_ack_oracle.other,
				   1, __ATOMIC_RELAXED);
	}
	return;

out_sendfail:
	__atomic_add_fetch(&shm->stats.rtnl_ack_oracle.send_fail,
			   1, __ATOMIC_RELAXED);
	return;

out_noreply:
	__atomic_add_fetch(&shm->stats.rtnl_ack_oracle.no_reply,
			   1, __ATOMIC_RELAXED);
}
