#!/bin/bash
#
# stats-opclock-lossless-suite: build and run the stats_opclock_lossless
# test suite under ASAN to gate the lossless op-count invariants.
#
# The test binary (tests/test-bin-asan) exercises the per-child
# lossless_op_count plausibility guards -- absolute ceiling, delta
# ceiling, and the first-drain scribble rejection path -- without
# importing the full trinity shm/ring stack.  The ASAN build catches
# memory errors that a plain debug build might mask.
#
# Invoked as part of `bash scripts/check-static.sh`; the top-level
# check-static loop passes REPO_ROOT so this script does not need to
# derive the root itself.
#
# Quiet on pass: only the PASS/FAIL line is written to stdout.  On
# failure, the full make output (captured to a temp file) is dumped
# to stderr so the developer can see which fixture failed and why.
#
# Exit codes:
#   0  -- test binary built and ran; all fixtures passed
#   1  -- build failed or at least one fixture failed

set -u

NAME="stats-opclock-lossless-suite"
ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"

out_tmp="$(mktemp)"
trap 'rm -f "$out_tmp"' EXIT

cd "$ROOT" || { echo "FAIL: $NAME: cannot cd to $ROOT"; exit 1; }

# Require config.h (generated by ./configure).  A missing config.h
# means the tree has not been configured; treat that as a hard error
# rather than silently skipping the test.
if [ ! -f config.h ]; then
	echo "FAIL: $NAME: config.h missing -- run ./configure first" >&2
	echo "FAIL: $NAME: config.h missing"
	exit 1
fi

# make test-asan: rebuilds tests/test-bin-asan incrementally (the
# flavor-keyed build-asan/ directory is not shared with the normal or
# NDEBUG builds) then runs it.  Output is captured; only stderr is
# preserved since the test binary writes failures there.
if ! make test-asan >"$out_tmp" 2>&1; then
	{
		echo "  $NAME: make test-asan failed; output follows:"
		sed 's/^/    /' "$out_tmp"
	} >&2
	echo "FAIL: $NAME: stats_opclock_lossless suite failed (see above)"
	exit 1
fi

echo "PASS: $NAME: all stats_opclock_lossless fixtures passed under ASAN"
exit 0
