/*
 * health/signals-policy.c — signal install/mask policy for parent and child.
 *
 * Owns the three volatile pending-flag globals, the watchdog handlers
 * (SIGALRM, SIGXCPU), the catch-all default-restore sighandler, and
 * the two public installers:
 *
 *   mask_signals_child()   — full child signal disposition table
 *   setup_main_signals()   — parent signal disposition table
 *
 * Handler ordering in mask_signals_child() is load-bearing: the
 * catch-all sighandler loop runs first (establishes a safe default for
 * every signal), then the per-signal overrides layer on top.  Do not
 * reorder the sigaction() calls without a careful review of the
 * window between sigprocmask(SIG_BLOCK) and sigprocmask(SIG_SETMASK).
 *
 * SERIALIZE with the signal() → sigaction() migrations for
 * the signal(sig, SIG_DFL) calls in sighandler() and main_fault_handler()
 * are that task's territory; do not modify those call sites here.
 *
 * See Documentation/signals.md.
 */
#include <signal.h>	/* sigaction, sigset_t, SA_SIGINFO, SA_RESTART */
#if defined(USE_BACKTRACE) && !defined(__SANITIZE_ADDRESS__)
#include <execinfo.h>	/* backtrace() -- pre-warm libgcc_s.so.1 */
#endif

#include "trinity.h"	/* __unused__, panic(), EXIT_SIGINT */
#include "signals.h"
#include "signals-internal.h"

#include "pids.h"	/* mypid(), mainpid */
#include "shm.h"	/* shm->stats (watchdog_reinstall_if_clobbered) */

volatile sig_atomic_t sigalrm_pending;
volatile sig_atomic_t xcpu_pending;
volatile sig_atomic_t ctrlc_pending;

/*
 * SA_SIGINFO version: only honor SIGINT generated by the kernel
 * (si_code > 0, e.g. SI_KERNEL from a terminal ctrl-c).  Any
 * userspace-sent SIGINT — including self-sent via raise()/
 * kill(getpid(), SIGINT)/tgkill(self, SIGINT) — is ignored.
 *
 * Trinity has no internal raise(SIGINT) callers, so a self-sent
 * SIGINT can only come from a child fuzzing the signal-delivery
 * syscalls and happening to pick signal 2 with its own pid as the
 * target.  Honoring those was causing spurious whole-run shutdowns:
 * the child would set ctrlc_pending, then panic(EXIT_SIGINT) on the
 * next loop iteration, the parent saw exit_reason flip, and ~77
 * fuzzing children got reaped for no real reason.
 *
 * Used by both parent and children.  The parent calls panic() directly;
 * children set ctrlc_pending and let the main loop exit cleanly.
 */
static void sigint_handler(__unused__ int sig, siginfo_t *info, __unused__ void *ctx)
{
	/* Only honor real terminal-generated SIGINT (si_code > 0).
	 * SI_USER (0) and below indicate userspace-sent — ignore as
	 * spoofable. */
	if (info->si_code > 0) {
		if (mypid() == mainpid)
			panic(EXIT_SIGINT);
		else
			ctrlc_pending = 1;
	}
}

static __attribute__((no_sanitize("address")))
void sighandler(int sig)
{
	/* Restore default disposition and re-raise so the kernel emits
	 * the usual crash artefacts (signal exit, dmesg log, core if
	 * enabled).  Silent _exit(SUCCESS) hid real fuzzer finds because
	 * the parent saw WIFEXITED(0) instead of WIFSIGNALED(sig). */
	(void)signal(sig, SIG_DFL);
	raise(sig);
}

void sigalrm_handler(__unused__ int sig)
{
	sigalrm_pending = 1;
	/* Don't siglongjmp here.  SIGALRM is installed without
	 * SA_RESTART, so the signal interrupts the blocking syscall
	 * (it returns EINTR/ERESTARTNOHAND) and control returns to
	 * the child main loop where sigalrm_pending is checked.
	 *
	 * The old code called siglongjmp() from here, which could
	 * permanently leak glibc's allocator lock if the child was
	 * inside malloc/free at signal delivery time, causing
	 * deadlock or heap corruption on the next allocation. */
}

void sigxcpu_handler(__unused__ int sig)
{
	xcpu_pending = 1;
	/* Don't siglongjmp here.  The signal interrupts the syscall
	 * (SIGXCPU is installed without SA_RESTART), and the child
	 * main loop checks xcpu_pending on the next iteration.
	 * Longjmping from here risked orphaning locks held at the
	 * time of the signal. */
}

void watchdog_reinstall_if_clobbered(void)
{
	struct sigaction cur;

	/* SIGALRM: reinstall the flag-setter if a fuzzed rt_sigaction
	 * has swapped it out.  Match the mask_signals_child() install:
	 * empty mask, no SA_RESTART, so the arriving signal interrupts
	 * the blocking syscall (EINTR) and control returns to the child
	 * main loop where sigalrm_pending is checked. */
	if (sigaction(SIGALRM, NULL, &cur) == 0 &&
	    cur.sa_handler != sigalrm_handler) {
		struct sigaction sa;
		sigemptyset(&sa.sa_mask);
		sa.sa_flags = 0;
		sa.sa_handler = sigalrm_handler;
		(void)sigaction(SIGALRM, &sa, NULL);
		__atomic_add_fetch(&shm->stats.watchdog_signal.sigalrm_clobbered,
				   1, __ATOMIC_RELAXED);
		__atomic_add_fetch(&shm->stats.watchdog_signal.sigalrm_reinstalled,
				   1, __ATOMIC_RELAXED);
	}

	/* SIGXCPU: same reinstall, same install parameters -- see
	 * mask_signals_child() for the sa_flags=0 rationale (interrupt
	 * the syscall, let the child main loop see xcpu_pending). */
	if (sigaction(SIGXCPU, NULL, &cur) == 0 &&
	    cur.sa_handler != sigxcpu_handler) {
		struct sigaction sa;
		sigemptyset(&sa.sa_mask);
		sa.sa_flags = 0;
		sa.sa_handler = sigxcpu_handler;
		(void)sigaction(SIGXCPU, &sa, NULL);
		__atomic_add_fetch(&shm->stats.watchdog_signal.sigxcpu_clobbered,
				   1, __ATOMIC_RELAXED);
		__atomic_add_fetch(&shm->stats.watchdog_signal.sigxcpu_reinstalled,
				   1, __ATOMIC_RELAXED);
	}
}

void mask_signals_child(void)
{
	struct sigaction sa;
	sigset_t ss, oldss;
	int i;

	/* Block all signals while we install handlers.  Without this,
	 * a signal arriving between the catch-all sighandler install
	 * and the proper handler install would silently _exit(SUCCESS),
	 * masking the real cause of the child's death. */
	sigfillset(&ss);
	sigprocmask(SIG_BLOCK, &ss, &oldss);

	for (i = 1; i < _NSIG; i++) {
		(void)sigfillset(&ss);
		sa.sa_flags = SA_RESTART;
		sa.sa_handler = sighandler;
		sa.sa_mask = ss;
		(void)sigaction(i, &sa, NULL);
	}
	/* we want default behaviour for child process signals */
	(void)signal(SIGCHLD, SIG_DFL);

	/* SIGALRM: set a flag and let the interrupted syscall return
	 * EINTR.  Installed without SA_RESTART so blocking syscalls
	 * are interrupted rather than silently restarted. */
	{
		struct sigaction alrm_sa;
		sigemptyset(&alrm_sa.sa_mask);
		alrm_sa.sa_flags = 0;
		alrm_sa.sa_handler = sigalrm_handler;
		(void)sigaction(SIGALRM, &alrm_sa, NULL);
	}

	/* Count SIGXCPUs.  Install without SA_RESTART so the signal
	 * interrupts blocking syscalls and control returns to the
	 * child main loop where xcpu_pending is checked. */
	{
		struct sigaction xcpu_sa;
		sigemptyset(&xcpu_sa.sa_mask);
		xcpu_sa.sa_flags = 0;
		xcpu_sa.sa_handler = sigxcpu_handler;
		(void)sigaction(SIGXCPU, &xcpu_sa, NULL);
	}

	/* Ignore terminal, job-control, async-IO and broken-pipe signals,
	 * plus SIGFPE/SIGXFSZ: none of these should terminate or stop a
	 * fuzzing child. */
	(void)signal(SIGFPE, SIG_IGN);
	(void)signal(SIGTSTP, SIG_IGN);
	(void)signal(SIGWINCH, SIG_IGN);
	(void)signal(SIGIO, SIG_IGN);
	(void)signal(SIGPIPE, SIG_IGN);
	(void)signal(SIGXFSZ, SIG_IGN);

	/* Ignore the RT signals. */
	for (i = SIGRTMIN; i <= SIGRTMAX; i++)
		(void)signal(i, SIG_IGN);

	/*
	 * Install child_fault_handler for the kernel-fault signals.
	 * Replaces both the catch-all sighandler (which silently
	 * _exit'd, masking the cause) and the debug-mode SIG_DFL
	 * override (which dumped a core but no inline backtrace).
	 * The handler dumps a backtrace + psiginfo to stderr in BOTH
	 * modes; in debug it then re-raises with SIG_DFL so the kernel
	 * still drops a core, in non-debug it _exit's cleanly so the
	 * parent's reaper doesn't see a crash and crash-loop.
	 */
	{
		struct sigaction fault_sa;
		sigemptyset(&fault_sa.sa_mask);
		fault_sa.sa_flags = SA_SIGINFO;
		fault_sa.sa_sigaction = child_fault_handler;
		(void)sigaction(SIGSEGV, &fault_sa, NULL);
		(void)sigaction(SIGABRT, &fault_sa, NULL);
		(void)sigaction(SIGBUS,  &fault_sa, NULL);
		(void)sigaction(SIGILL,  &fault_sa, NULL);
	}

	/*
	 * SIGTRAP handler for the Stage-2 writer-pinning canary HW
	 * watchpoint (--writer-watch).  Installed unconditionally so the
	 * disposition is the same shape regardless of whether the perf
	 * event has been armed yet; writer_watch_arm_child() is what
	 * actually opens the perf fd and routes SIGTRAP here via
	 * F_SETSIG.  When --writer-watch is not in use the perf fd is
	 * never opened, no SIGTRAP can fire, and the handler is dead
	 * code.  SA_SIGINFO so the handler can read the ucontext for the
	 * writer's RIP and the siginfo for the watched address.
	 */
	{
		struct sigaction trap_sa;
		sigemptyset(&trap_sa.sa_mask);
		trap_sa.sa_flags = SA_SIGINFO;
		trap_sa.sa_sigaction = writer_trap_handler;
		(void)sigaction(SIGTRAP, &trap_sa, NULL);
	}

	/* trap ctrl-c — use SA_SIGINFO so we can ignore child-sent SIGINTs,
	 * same as the parent handler. Without this, children fuzzing
	 * rt_tgsigqueueinfo/kill with SIGINT cause phantom ctrl-c exits. */
	{
		struct sigaction int_sa;
		sigemptyset(&int_sa.sa_mask);
		int_sa.sa_flags = SA_SIGINFO;
		int_sa.sa_sigaction = sigint_handler;
		(void)sigaction(SIGINT, &int_sa, NULL);
	}

	/* All handlers installed — unblock signals. */
	sigprocmask(SIG_SETMASK, &oldss, NULL);
}


void setup_main_signals(void)
{
	struct sigaction sa;
	int i;

	(void)signal(SIGCHLD, SIG_DFL);

	/*
	 * Ignore signals that children can send us via kill/tkill/tgkill.
	 * Without this, the fuzzer randomly terminates when a child happens
	 * to send a fatal signal to the parent PID.
	 */
	(void)signal(SIGHUP, SIG_IGN);
	(void)signal(SIGUSR1, SIG_IGN);
	(void)signal(SIGUSR2, SIG_IGN);
	(void)signal(SIGALRM, SIG_IGN);
	(void)signal(SIGTERM, SIG_IGN);
	(void)signal(SIGVTALRM, SIG_IGN);
	(void)signal(SIGPROF, SIG_IGN);
	(void)signal(SIGXFSZ, SIG_IGN);
	(void)signal(SIGXCPU, SIG_IGN);
	(void)signal(SIGPIPE, SIG_IGN);
	(void)signal(SIGIO, SIG_IGN);

	/* Ignore RT signals — children fuzzing rt_sigqueueinfo,
	 * pidfd_send_signal, timer_create/settime with sigev_signo in
	 * [SIGRTMIN..SIGRTMAX], etc. can deliver any RT signal to us.
	 * Default kernel action for an unhandled RT signal is termination,
	 * which silently exits trinity ("Real-time signal N" printed by
	 * glibc).  Mirror the same loop the children use in mask_signals_child. */
	for (i = SIGRTMIN; i <= SIGRTMAX; i++)
		(void)signal(i, SIG_IGN);

	/*
	 * Use SA_SIGINFO for fault/core-dump signals so we can distinguish
	 * real faults (si_code > 0, from kernel) from signals sent by child
	 * processes fuzzing kill/tkill/tgkill (si_code <= 0).
	 */
	sigemptyset(&sa.sa_mask);
	sa.sa_flags = SA_SIGINFO;
	sa.sa_sigaction = main_fault_handler;
	(void)sigaction(SIGABRT, &sa, NULL);
	(void)sigaction(SIGSEGV, &sa, NULL);
	(void)sigaction(SIGBUS, &sa, NULL);
	(void)sigaction(SIGILL, &sa, NULL);
	(void)sigaction(SIGFPE, &sa, NULL);
	(void)sigaction(SIGQUIT, &sa, NULL);
	(void)sigaction(SIGTRAP, &sa, NULL);
	(void)sigaction(SIGSYS, &sa, NULL);

	/* SIGINT: use SA_SIGINFO so we can ignore child-sent SIGINTs.
	 * Real ctrl-c from the terminal has si_code > 0 (SI_KERNEL). */
	sa.sa_sigaction = sigint_handler;
	(void)sigaction(SIGINT, &sa, NULL);

	/*
	 * Eager-load libgcc_s.so.1 by calling backtrace() once now, while
	 * malloc is healthy and no fault handler can fire.  The first
	 * backtrace() in a process triggers
	 *   libc_unwind_link_get -> __libc_dlopen_mode("libgcc_s.so.1")
	 *     -> _dl_load_cache_lookup -> strdup -> malloc
	 * If we instead reach backtrace() for the first time from the
	 * SIGABRT handler raised by a glibc malloc assertion (heap
	 * corruption -> abort), the main_arena lock is already held by
	 * this very thread.  The recursive malloc inside dlopen then
	 * deadlocks forever in lll_lock_wait_private and we lose every
	 * child to a futex_wait we cannot recover from -- the diagnostic
	 * machinery itself becomes the bug.
	 *
	 * Doing it here, in the parent before fork, ensures libgcc_s is
	 * already mapped in every child via copy-on-write inheritance, so
	 * neither child_fault_handler nor main_fault_handler can hit the
	 * dlopen path at signal time.
	 */
#if defined(USE_BACKTRACE) && !defined(__SANITIZE_ADDRESS__)
	{
		void *stub[1];
		(void)backtrace(stub, 1);
	}
#endif
}
