#include <linux/videodev2.h>

#include "utils.h"
#include "ioctls.h"

/*
 * Compile-time: every fixed-shape v4l2 ioctl command in the table
 * below whose arg is a kernel struct must have sizeof(struct)
 * matching the _IOC_SIZE encoded in its request bits.  A mismatch
 * means videodev2.h moved under us and the request bits now encode a
 * different struct than we're passing (or vice versa) -- either
 * short of the kernel's copy_from_user() / copy_to_user() or past
 * it.  Commands sharing a struct (VIDIOC_G_FMT / VIDIOC_S_FMT /
 * VIDIOC_TRY_FMT all take v4l2_format; VIDIOC_QUERYBUF / VIDIOC_QBUF
 * / VIDIOC_DQBUF / VIDIOC_PREPARE_BUF all take v4l2_buffer; and so
 * on for the other _G / _S / _TRY / _ENUM / _CMD families below) get
 * one assert each -- the sides can drift independently in a header
 * refactor.  Per-cmd #ifdef guards mirror the ioctl-table wrapping
 * so builds against older uapi headers that predate a command still
 * compile.
 *
 * VIDIOC_OVERLAY, VIDIOC_STREAMON, VIDIOC_STREAMOFF, VIDIOC_G_INPUT,
 * VIDIOC_S_INPUT, VIDIOC_G_OUTPUT, VIDIOC_S_OUTPUT encode a bare
 * int; VIDIOC_G_STD, VIDIOC_S_STD and VIDIOC_QUERYSTD encode
 * v4l2_std_id (a bare __u64); VIDIOC_G_PRIORITY and
 * VIDIOC_S_PRIORITY encode a bare __u32; VIDIOC_LOG_STATUS is _IO()
 * with no arg.  All are intentionally absent -- asserting
 * sizeof(struct) against a scalar or a zero _IOC_SIZE would be the
 * wrong shape of check.
 */
IOCTL_SIZE_ASSERT(VIDIOC_QUERYCAP, struct v4l2_capability);
IOCTL_SIZE_ASSERT(VIDIOC_ENUM_FMT, struct v4l2_fmtdesc);
IOCTL_SIZE_ASSERT(VIDIOC_G_FMT, struct v4l2_format);
IOCTL_SIZE_ASSERT(VIDIOC_S_FMT, struct v4l2_format);
IOCTL_SIZE_ASSERT(VIDIOC_TRY_FMT, struct v4l2_format);
IOCTL_SIZE_ASSERT(VIDIOC_REQBUFS, struct v4l2_requestbuffers);
IOCTL_SIZE_ASSERT(VIDIOC_QUERYBUF, struct v4l2_buffer);
IOCTL_SIZE_ASSERT(VIDIOC_QBUF, struct v4l2_buffer);
IOCTL_SIZE_ASSERT(VIDIOC_DQBUF, struct v4l2_buffer);
IOCTL_SIZE_ASSERT(VIDIOC_G_FBUF, struct v4l2_framebuffer);
IOCTL_SIZE_ASSERT(VIDIOC_S_FBUF, struct v4l2_framebuffer);
#ifdef VIDIOC_EXPBUF
IOCTL_SIZE_ASSERT(VIDIOC_EXPBUF, struct v4l2_exportbuffer);
#endif
IOCTL_SIZE_ASSERT(VIDIOC_G_PARM, struct v4l2_streamparm);
IOCTL_SIZE_ASSERT(VIDIOC_S_PARM, struct v4l2_streamparm);
IOCTL_SIZE_ASSERT(VIDIOC_ENUMSTD, struct v4l2_standard);
IOCTL_SIZE_ASSERT(VIDIOC_ENUMINPUT, struct v4l2_input);
IOCTL_SIZE_ASSERT(VIDIOC_G_CTRL, struct v4l2_control);
IOCTL_SIZE_ASSERT(VIDIOC_S_CTRL, struct v4l2_control);
IOCTL_SIZE_ASSERT(VIDIOC_G_TUNER, struct v4l2_tuner);
IOCTL_SIZE_ASSERT(VIDIOC_S_TUNER, struct v4l2_tuner);
IOCTL_SIZE_ASSERT(VIDIOC_G_AUDIO, struct v4l2_audio);
IOCTL_SIZE_ASSERT(VIDIOC_S_AUDIO, struct v4l2_audio);
IOCTL_SIZE_ASSERT(VIDIOC_QUERYCTRL, struct v4l2_queryctrl);
IOCTL_SIZE_ASSERT(VIDIOC_QUERYMENU, struct v4l2_querymenu);
IOCTL_SIZE_ASSERT(VIDIOC_ENUMOUTPUT, struct v4l2_output);
IOCTL_SIZE_ASSERT(VIDIOC_G_AUDOUT, struct v4l2_audioout);
IOCTL_SIZE_ASSERT(VIDIOC_S_AUDOUT, struct v4l2_audioout);
IOCTL_SIZE_ASSERT(VIDIOC_G_MODULATOR, struct v4l2_modulator);
IOCTL_SIZE_ASSERT(VIDIOC_S_MODULATOR, struct v4l2_modulator);
IOCTL_SIZE_ASSERT(VIDIOC_G_FREQUENCY, struct v4l2_frequency);
IOCTL_SIZE_ASSERT(VIDIOC_S_FREQUENCY, struct v4l2_frequency);
IOCTL_SIZE_ASSERT(VIDIOC_CROPCAP, struct v4l2_cropcap);
IOCTL_SIZE_ASSERT(VIDIOC_G_CROP, struct v4l2_crop);
IOCTL_SIZE_ASSERT(VIDIOC_S_CROP, struct v4l2_crop);
IOCTL_SIZE_ASSERT(VIDIOC_G_JPEGCOMP, struct v4l2_jpegcompression);
IOCTL_SIZE_ASSERT(VIDIOC_S_JPEGCOMP, struct v4l2_jpegcompression);
IOCTL_SIZE_ASSERT(VIDIOC_ENUMAUDIO, struct v4l2_audio);
IOCTL_SIZE_ASSERT(VIDIOC_ENUMAUDOUT, struct v4l2_audioout);
IOCTL_SIZE_ASSERT(VIDIOC_G_SLICED_VBI_CAP, struct v4l2_sliced_vbi_cap);
IOCTL_SIZE_ASSERT(VIDIOC_G_EXT_CTRLS, struct v4l2_ext_controls);
IOCTL_SIZE_ASSERT(VIDIOC_S_EXT_CTRLS, struct v4l2_ext_controls);
IOCTL_SIZE_ASSERT(VIDIOC_TRY_EXT_CTRLS, struct v4l2_ext_controls);
IOCTL_SIZE_ASSERT(VIDIOC_ENUM_FRAMESIZES, struct v4l2_frmsizeenum);
IOCTL_SIZE_ASSERT(VIDIOC_ENUM_FRAMEINTERVALS, struct v4l2_frmivalenum);
IOCTL_SIZE_ASSERT(VIDIOC_G_ENC_INDEX, struct v4l2_enc_idx);
IOCTL_SIZE_ASSERT(VIDIOC_ENCODER_CMD, struct v4l2_encoder_cmd);
IOCTL_SIZE_ASSERT(VIDIOC_TRY_ENCODER_CMD, struct v4l2_encoder_cmd);
IOCTL_SIZE_ASSERT(VIDIOC_DBG_S_REGISTER, struct v4l2_dbg_register);
IOCTL_SIZE_ASSERT(VIDIOC_DBG_G_REGISTER, struct v4l2_dbg_register);
IOCTL_SIZE_ASSERT(VIDIOC_S_HW_FREQ_SEEK, struct v4l2_hw_freq_seek);
#ifdef VIDIOC_S_DV_TIMINGS
IOCTL_SIZE_ASSERT(VIDIOC_S_DV_TIMINGS, struct v4l2_dv_timings);
#endif
#ifdef VIDIOC_G_DV_TIMINGS
IOCTL_SIZE_ASSERT(VIDIOC_G_DV_TIMINGS, struct v4l2_dv_timings);
#endif
#ifdef VIDIOC_DQEVENT
IOCTL_SIZE_ASSERT(VIDIOC_DQEVENT, struct v4l2_event);
#endif
#ifdef VIDIOC_SUBSCRIBE_EVENT
IOCTL_SIZE_ASSERT(VIDIOC_SUBSCRIBE_EVENT, struct v4l2_event_subscription);
#endif
#ifdef VIDIOC_UNSUBSCRIBE_EVENT
IOCTL_SIZE_ASSERT(VIDIOC_UNSUBSCRIBE_EVENT, struct v4l2_event_subscription);
#endif
#ifdef VIDIOC_CREATE_BUFS
IOCTL_SIZE_ASSERT(VIDIOC_CREATE_BUFS, struct v4l2_create_buffers);
#endif
#ifdef VIDIOC_PREPARE_BUF
IOCTL_SIZE_ASSERT(VIDIOC_PREPARE_BUF, struct v4l2_buffer);
#endif
#ifdef VIDIOC_G_SELECTION
IOCTL_SIZE_ASSERT(VIDIOC_G_SELECTION, struct v4l2_selection);
#endif
#ifdef VIDIOC_S_SELECTION
IOCTL_SIZE_ASSERT(VIDIOC_S_SELECTION, struct v4l2_selection);
#endif
#ifdef VIDIOC_DECODER_CMD
IOCTL_SIZE_ASSERT(VIDIOC_DECODER_CMD, struct v4l2_decoder_cmd);
#endif
#ifdef VIDIOC_TRY_DECODER_CMD
IOCTL_SIZE_ASSERT(VIDIOC_TRY_DECODER_CMD, struct v4l2_decoder_cmd);
#endif
#ifdef VIDIOC_ENUM_DV_TIMINGS
IOCTL_SIZE_ASSERT(VIDIOC_ENUM_DV_TIMINGS, struct v4l2_enum_dv_timings);
#endif
#ifdef VIDIOC_QUERY_DV_TIMINGS
IOCTL_SIZE_ASSERT(VIDIOC_QUERY_DV_TIMINGS, struct v4l2_dv_timings);
#endif
#ifdef VIDIOC_DV_TIMINGS_CAP
IOCTL_SIZE_ASSERT(VIDIOC_DV_TIMINGS_CAP, struct v4l2_dv_timings_cap);
#endif
#ifdef VIDIOC_ENUM_FREQ_BANDS
IOCTL_SIZE_ASSERT(VIDIOC_ENUM_FREQ_BANDS, struct v4l2_frequency_band);
#endif

static const struct ioctl videodev2_ioctls[] = {
	IOCTL(VIDIOC_QUERYCAP),
#ifdef VIDIOC_RESERVED
	IOCTL(VIDIOC_RESERVED),
#endif
	IOCTL(VIDIOC_ENUM_FMT),
	IOCTL(VIDIOC_G_FMT),
	IOCTL(VIDIOC_S_FMT),
	IOCTL(VIDIOC_REQBUFS),
	IOCTL(VIDIOC_QUERYBUF),
	IOCTL(VIDIOC_G_FBUF),
	IOCTL(VIDIOC_S_FBUF),
	IOCTL(VIDIOC_OVERLAY),
	IOCTL(VIDIOC_QBUF),
#ifdef VIDIOC_EXPBUF
	IOCTL(VIDIOC_EXPBUF),
#endif
	IOCTL(VIDIOC_DQBUF),
	IOCTL(VIDIOC_STREAMON),
	IOCTL(VIDIOC_STREAMOFF),
	IOCTL(VIDIOC_G_PARM),
	IOCTL(VIDIOC_S_PARM),
	IOCTL(VIDIOC_G_STD),
	IOCTL(VIDIOC_S_STD),
	IOCTL(VIDIOC_ENUMSTD),
	IOCTL(VIDIOC_ENUMINPUT),
	IOCTL(VIDIOC_G_CTRL),
	IOCTL(VIDIOC_S_CTRL),
	IOCTL(VIDIOC_G_TUNER),
	IOCTL(VIDIOC_S_TUNER),
	IOCTL(VIDIOC_G_AUDIO),
	IOCTL(VIDIOC_S_AUDIO),
	IOCTL(VIDIOC_QUERYCTRL),
	IOCTL(VIDIOC_QUERYMENU),
	IOCTL(VIDIOC_G_INPUT),
	IOCTL(VIDIOC_S_INPUT),
	IOCTL(VIDIOC_G_OUTPUT),
	IOCTL(VIDIOC_S_OUTPUT),
	IOCTL(VIDIOC_ENUMOUTPUT),
	IOCTL(VIDIOC_G_AUDOUT),
	IOCTL(VIDIOC_S_AUDOUT),
	IOCTL(VIDIOC_G_MODULATOR),
	IOCTL(VIDIOC_S_MODULATOR),
	IOCTL(VIDIOC_G_FREQUENCY),
	IOCTL(VIDIOC_S_FREQUENCY),
	IOCTL(VIDIOC_CROPCAP),
	IOCTL(VIDIOC_G_CROP),
	IOCTL(VIDIOC_S_CROP),
	IOCTL(VIDIOC_G_JPEGCOMP),
	IOCTL(VIDIOC_S_JPEGCOMP),
	IOCTL(VIDIOC_QUERYSTD),
	IOCTL(VIDIOC_TRY_FMT),
	IOCTL(VIDIOC_ENUMAUDIO),
	IOCTL(VIDIOC_ENUMAUDOUT),
	IOCTL(VIDIOC_G_PRIORITY),
	IOCTL(VIDIOC_S_PRIORITY),
	IOCTL(VIDIOC_G_SLICED_VBI_CAP),
	IOCTL(VIDIOC_LOG_STATUS),
	IOCTL(VIDIOC_G_EXT_CTRLS),
	IOCTL(VIDIOC_S_EXT_CTRLS),
	IOCTL(VIDIOC_TRY_EXT_CTRLS),
	IOCTL(VIDIOC_ENUM_FRAMESIZES),
	IOCTL(VIDIOC_ENUM_FRAMEINTERVALS),
	IOCTL(VIDIOC_G_ENC_INDEX),
	IOCTL(VIDIOC_ENCODER_CMD),
	IOCTL(VIDIOC_TRY_ENCODER_CMD),
	IOCTL(VIDIOC_DBG_S_REGISTER),
	IOCTL(VIDIOC_DBG_G_REGISTER),
#ifdef VIDIOC_DBG_G_CHIP_IDENT
	IOCTL(VIDIOC_DBG_G_CHIP_IDENT),
#endif
	IOCTL(VIDIOC_S_HW_FREQ_SEEK),
#ifdef VIDIOC_ENUM_DV_PRESETS
	IOCTL(VIDIOC_ENUM_DV_PRESETS),
#endif
#ifdef VIDIOC_S_DV_PRESET
	IOCTL(VIDIOC_S_DV_PRESET),
#endif
#ifdef VIDIOC_G_DV_PRESET
	IOCTL(VIDIOC_G_DV_PRESET),
#endif
#ifdef VIDIOC_QUERY_DV_PRESET
	IOCTL(VIDIOC_QUERY_DV_PRESET),
#endif
#ifdef VIDIOC_S_DV_TIMINGS
	IOCTL(VIDIOC_S_DV_TIMINGS),
#endif
#ifdef VIDIOC_G_DV_TIMINGS
	IOCTL(VIDIOC_G_DV_TIMINGS),
#endif
#ifdef VIDIOC_DQEVENT
	IOCTL(VIDIOC_DQEVENT),
#endif
#ifdef VIDIOC_SUBSCRIBE_EVENT
	IOCTL(VIDIOC_SUBSCRIBE_EVENT),
#endif
#ifdef VIDIOC_UNSUBSCRIBE_EVENT
	IOCTL(VIDIOC_UNSUBSCRIBE_EVENT),
#endif
#ifdef VIDIOC_CREATE_BUFS
	IOCTL(VIDIOC_CREATE_BUFS),
#endif
#ifdef VIDIOC_PREPARE_BUF
	IOCTL(VIDIOC_PREPARE_BUF),
#endif
#ifdef VIDIOC_G_SELECTION
	IOCTL(VIDIOC_G_SELECTION),
#endif
#ifdef VIDIOC_S_SELECTION
	IOCTL(VIDIOC_S_SELECTION),
#endif
#ifdef VIDIOC_DECODER_CMD
	IOCTL(VIDIOC_DECODER_CMD),
#endif
#ifdef VIDIOC_TRY_DECODER_CMD
	IOCTL(VIDIOC_TRY_DECODER_CMD),
#endif
#ifdef VIDIOC_ENUM_DV_TIMINGS
	IOCTL(VIDIOC_ENUM_DV_TIMINGS),
#endif
#ifdef VIDIOC_QUERY_DV_TIMINGS
	IOCTL(VIDIOC_QUERY_DV_TIMINGS),
#endif
#ifdef VIDIOC_DV_TIMINGS_CAP
	IOCTL(VIDIOC_DV_TIMINGS_CAP),
#endif
#ifdef VIDIOC_ENUM_FREQ_BANDS
	IOCTL(VIDIOC_ENUM_FREQ_BANDS),
#endif
};

static const char *const videodev2_devs[] = {
	"video4linux",
};

static const struct ioctl_group videodev2_grp = {
	.devtype = DEV_MISC,
	.devs = videodev2_devs,
	.devs_cnt = ARRAY_SIZE(videodev2_devs),
	.sanitise = pick_random_ioctl,
	.ioctls = videodev2_ioctls,
	.ioctls_cnt = ARRAY_SIZE(videodev2_ioctls),
};

REG_IOCTL_GROUP(videodev2_grp)
