#define KERNEL_ADDR	0xc0000000
#define PAGE_OFFSET 0xC0000000
#define TASK_SIZE (PAGE_OFFSET)

#define PAGE_SHIFT 12
#define BITS_PER_LONG 64
#define PTE_RPN_SHIFT   (PAGE_SHIFT)
#define PTE_FILE_MAX_BITS       (BITS_PER_LONG - PTE_RPN_SHIFT)
