#ifndef _CONSTANTS_H
#define _CONSTANTS_H 1

#define MAX_NR_CHILDREN 64

#define MAX_PIPE_FDS 4
#define NR_SOCKET_FDS 375
#define NR_FILE_FDS 250

#define REGENERATION_POINT 100000

#endif	/* _CONSTANTS_H */
