#pragma once

enum objecttype {
	/*
	 * Sentinel placed at slot 0 so a default-initialised
	 * ret_objtype field (zero) reads as "no fd to track".
	 * All real types follow; the cost is one unused objhead
	 * slot in every per-scope array.
	 */
	OBJ_NONE,
	OBJ_MMAP_ANON,
	OBJ_MMAP_FILE,
	OBJ_MMAP_TESTFILE,
	OBJ_FD_PIPE,
	OBJ_FD_DEVFILE,
	OBJ_FD_PROCFILE,
	OBJ_FD_SYSFILE,
	OBJ_FD_PERF,
	OBJ_FD_EPOLL,
	OBJ_FD_EVENTFD,
	OBJ_FD_TIMERFD,
	OBJ_FD_TESTFILE,
	OBJ_FD_MEMFD,
	OBJ_FD_MEMFD_SECRET,
	OBJ_FD_DRM,
	OBJ_FD_INOTIFY,
	OBJ_FD_SOCKET,
	OBJ_FD_USERFAULTFD,
	OBJ_FD_FANOTIFY,
	OBJ_FD_BPF_MAP,
	OBJ_FD_BPF_PROG,
	OBJ_FD_BPF_LINK,
	OBJ_FD_BPF_BTF,
	OBJ_FD_IO_URING,
	OBJ_FD_LANDLOCK,
	OBJ_FD_PIDFD,
	OBJ_FD_MQ,
	OBJ_FD_SECCOMP_NOTIF,
	OBJ_FD_IOMMUFD,
	OBJ_FD_FS_CTX,
	OBJ_FD_KVM_SYSTEM,
	OBJ_FD_KVM_VM,
	OBJ_FD_KVM_VCPU,
	OBJ_FD_PAGECACHE,
	OBJ_FD_SIGNALFD,
	OBJ_FD_MOUNT,
	OBJ_FD_CGROUP,
	OBJ_FD_WATCH_QUEUE,
	OBJ_AIO_CTX,
	OBJ_FUTEX,
	OBJ_FUTEX_SHARED,
	OBJ_SYSV_SHM,
	MAX_OBJECT_TYPES,
};

enum obj_scope {
	OBJ_LOCAL,
	OBJ_GLOBAL,
};
