/*
 * userns_fuzzer - enter a fresh user namespace as uid 0, then exercise
 * the kernel attack surface that ns_capable() opens up to unprivileged
 * users.
 *
 * Background: trinity's main fuzzer historically refuses to enter
 * CLONE_NEWUSER because doing so drops the real capabilities most
 * privileged syscalls require, which would tank the hit-rate against
 * the privileged code paths trinity is built to exercise.  But that
 * deliberate avoidance also means trinity never touches the
 * unprivileged-user-namespace attack surface — a class of code paths
 * that is the dominant local-privesc vector in modern kernels (every
 * ns_capable() check is a potential bypass point).
 *
 * Per call we fork an inner child, enter a fresh user namespace, map
 * uid 0 in the namespace to our real uid outside it, then dispatch one
 * randomly-chosen ns_capable()-gated syscall with mostly-trivial
 * arguments.  The inner child exits with _exit() so a crash inside the
 * userns is contained and reaped here without disturbing trinity's
 * outer state.
 *
 * Args are deliberately not generated by trinity's normal sanitisers:
 * those assume the regular trinity privilege state and pull from shared
 * object pools that the inner child shouldn't pollute.  A small inline
 * dispatcher keeps the inner-fuzzer body self-contained.
 *
 * Required kernel support: CONFIG_USER_NS=y and
 * /proc/sys/user/max_user_namespaces > 0.  Distros that disable
 * unprivileged user namespaces (e.g. user.max_user_namespaces=0,
 * kernel.unprivileged_userns_clone=0) cause unshare() to fail with
 * -EPERM; we detect that on first call, latch a per-process flag, and
 * become a noop afterwards rather than spamming the kernel with
 * doomed unshare() requests.
 *
 * Future enhancement: combine with the credential-consistency oracle
 * to verify that uid_map/gid_map mappings have the expected effect
 * inside the namespace, and explore nested CLONE_NEWUSER stacks
 * (kernel has historically had bugs around the depth limit).
 */

#define _GNU_SOURCE
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

#include "child.h"
#include "shm.h"
#include "trinity.h"

/*
 * Latched once per trinity-child process: if the kernel refuses
 * unshare(CLONE_NEWUSER) we don't try again from this child.  Each
 * trinity child gets its own copy of this static, which is fine — the
 * state is per-process and unshare() is cheap to retry across the fleet
 * if the system policy changes mid-run.
 */
static bool userns_disabled;
static bool warned_unsupported;

/*
 * Write the single-line idmap that maps uid/gid 0 inside the new
 * userns to our real outer uid/gid.  Returns true on success.
 */
static bool write_one_line(const char *path, const char *line)
{
	ssize_t wlen;
	size_t len;
	int fd;

	fd = open(path, O_WRONLY);
	if (fd < 0)
		return false;

	len = strlen(line);
	wlen = write(fd, line, len);
	close(fd);
	return wlen == (ssize_t)len;
}

/*
 * Establish uid 0 inside the freshly-entered userns.  setgroups must
 * be denied before gid_map can be written when the writer is
 * unprivileged, per Documentation/admin-guide/namespaces/user.rst.
 */
static bool establish_root_in_userns(void)
{
	char buf[64];
	uid_t uid = getuid();
	gid_t gid = getgid();

	snprintf(buf, sizeof(buf), "0 %u 1\n", (unsigned int)uid);
	if (!write_one_line("/proc/self/uid_map", buf))
		return false;

	if (!write_one_line("/proc/self/setgroups", "deny\n"))
		return false;

	snprintf(buf, sizeof(buf), "0 %u 1\n", (unsigned int)gid);
	if (!write_one_line("/proc/self/gid_map", buf))
		return false;

	return true;
}

/*
 * Inner-fuzzer body.  Will be replaced in a follow-up commit with a
 * curated dispatcher of ns_capable()-gated syscalls.  Until then the
 * inner child just enters the namespace, proves uid 0 was established,
 * and exits — exercising the userns setup path itself.
 */
static void run_inner_fuzzer(void)
{
}

/*
 * Inner-child entry: enter userns, set up id maps, dispatch one
 * fuzzer op, exit.  All exits use _exit() to skip atexit handlers
 * that could touch trinity shared state from a context where caps
 * don't match what they expect.
 */
static void inner_child_main(void)
{
	if (unshare(CLONE_NEWUSER) != 0)
		_exit(1);

	if (!establish_root_in_userns())
		_exit(2);

	run_inner_fuzzer();
	_exit(0);
}

bool userns_fuzzer(struct childdata *child)
{
	pid_t pid;
	int status;

	(void)child;

	if (userns_disabled)
		return true;

	__atomic_add_fetch(&shm->stats.userns_runs, 1, __ATOMIC_RELAXED);

	pid = fork();
	if (pid < 0)
		return true;

	if (pid == 0) {
		inner_child_main();
		_exit(0);	/* unreachable */
	}

	if (waitpid(pid, &status, 0) < 0)
		return true;

	if (WIFEXITED(status) && WEXITSTATUS(status) == 1) {
		/*
		 * unshare(CLONE_NEWUSER) failed — almost certainly EPERM
		 * from a hardened policy.  Latch a flag and warn once so
		 * subsequent calls noop instead of forking a child only to
		 * have it die immediately.
		 */
		userns_disabled = true;
		__atomic_add_fetch(&shm->stats.userns_unsupported,
				   1, __ATOMIC_RELAXED);
		if (!warned_unsupported) {
			warned_unsupported = true;
			output(0, "userns_fuzzer: CLONE_NEWUSER refused, disabling for this child\n");
		}
		return true;
	}

	if (WIFSIGNALED(status))
		__atomic_add_fetch(&shm->stats.userns_inner_crashed,
				   1, __ATOMIC_RELAXED);

	return true;
}
