#pragma once

/*
 * Wrapper around <linux/thermal.h> that ships per-symbol #ifndef-guarded
 * fallbacks for THERMAL_GENL_ATTR_* / THERMAL_GENL_CMD_* ids added after
 * our installed uapi header.  Build hosts whose <linux/thermal.h>
 * predates a given attribute (the post-6.7 CPU_CAPABILITY /
 * CPU_CAPABILITY_ID / CPU_CAPABILITY_PERFORMANCE / CPU_CAPABILITY_EFFICIENCY
 * quadruple, the post-6.10 THRESHOLD / THRESHOLD_TEMP / THRESHOLD_DIRECTION
 * triple) silently miss it from the validator coverage; the fallback
 * values match the upstream uapi enum ordering so the wire-format ids
 * the kernel parses match the ones the generator emits.
 * THERMAL_GENL_CMD_THRESHOLD_GET likewise falls back to the upstream
 * enum value.
 */
#include <linux/thermal.h>

#ifndef THERMAL_NAME_LENGTH
#define THERMAL_NAME_LENGTH			20
#endif

#ifndef THERMAL_GENL_ATTR_TZ
#define THERMAL_GENL_ATTR_TZ			1
#endif
#ifndef THERMAL_GENL_ATTR_TZ_ID
#define THERMAL_GENL_ATTR_TZ_ID			2
#endif
#ifndef THERMAL_GENL_ATTR_TZ_TEMP
#define THERMAL_GENL_ATTR_TZ_TEMP		3
#endif
#ifndef THERMAL_GENL_ATTR_TZ_TRIP
#define THERMAL_GENL_ATTR_TZ_TRIP		4
#endif
#ifndef THERMAL_GENL_ATTR_TZ_TRIP_ID
#define THERMAL_GENL_ATTR_TZ_TRIP_ID		5
#endif
#ifndef THERMAL_GENL_ATTR_TZ_TRIP_TYPE
#define THERMAL_GENL_ATTR_TZ_TRIP_TYPE		6
#endif
#ifndef THERMAL_GENL_ATTR_TZ_TRIP_TEMP
#define THERMAL_GENL_ATTR_TZ_TRIP_TEMP		7
#endif
#ifndef THERMAL_GENL_ATTR_TZ_TRIP_HYST
#define THERMAL_GENL_ATTR_TZ_TRIP_HYST		8
#endif
#ifndef THERMAL_GENL_ATTR_TZ_MODE
#define THERMAL_GENL_ATTR_TZ_MODE		9
#endif
#ifndef THERMAL_GENL_ATTR_TZ_NAME
#define THERMAL_GENL_ATTR_TZ_NAME		10
#endif
#ifndef THERMAL_GENL_ATTR_TZ_CDEV_WEIGHT
#define THERMAL_GENL_ATTR_TZ_CDEV_WEIGHT	11
#endif
#ifndef THERMAL_GENL_ATTR_TZ_GOV
#define THERMAL_GENL_ATTR_TZ_GOV		12
#endif
#ifndef THERMAL_GENL_ATTR_TZ_GOV_NAME
#define THERMAL_GENL_ATTR_TZ_GOV_NAME		13
#endif
#ifndef THERMAL_GENL_ATTR_CDEV
#define THERMAL_GENL_ATTR_CDEV			14
#endif
#ifndef THERMAL_GENL_ATTR_CDEV_ID
#define THERMAL_GENL_ATTR_CDEV_ID		15
#endif
#ifndef THERMAL_GENL_ATTR_CDEV_CUR_STATE
#define THERMAL_GENL_ATTR_CDEV_CUR_STATE	16
#endif
#ifndef THERMAL_GENL_ATTR_CDEV_MAX_STATE
#define THERMAL_GENL_ATTR_CDEV_MAX_STATE	17
#endif
#ifndef THERMAL_GENL_ATTR_CDEV_NAME
#define THERMAL_GENL_ATTR_CDEV_NAME		18
#endif
#ifndef THERMAL_GENL_ATTR_CPU_CAPABILITY
#define THERMAL_GENL_ATTR_CPU_CAPABILITY	20
#endif
#ifndef THERMAL_GENL_ATTR_CPU_CAPABILITY_ID
#define THERMAL_GENL_ATTR_CPU_CAPABILITY_ID	21
#endif
#ifndef THERMAL_GENL_ATTR_CPU_CAPABILITY_PERFORMANCE
#define THERMAL_GENL_ATTR_CPU_CAPABILITY_PERFORMANCE	22
#endif
#ifndef THERMAL_GENL_ATTR_CPU_CAPABILITY_EFFICIENCY
#define THERMAL_GENL_ATTR_CPU_CAPABILITY_EFFICIENCY	23
#endif
#ifndef THERMAL_GENL_ATTR_THRESHOLD
#define THERMAL_GENL_ATTR_THRESHOLD		24
#endif
#ifndef THERMAL_GENL_ATTR_THRESHOLD_TEMP
#define THERMAL_GENL_ATTR_THRESHOLD_TEMP	25
#endif
#ifndef THERMAL_GENL_ATTR_THRESHOLD_DIRECTION
#define THERMAL_GENL_ATTR_THRESHOLD_DIRECTION	26
#endif

#ifndef THERMAL_GENL_CMD_TZ_GET_ID
#define THERMAL_GENL_CMD_TZ_GET_ID		1
#endif
#ifndef THERMAL_GENL_CMD_TZ_GET_TRIP
#define THERMAL_GENL_CMD_TZ_GET_TRIP		2
#endif
#ifndef THERMAL_GENL_CMD_TZ_GET_TEMP
#define THERMAL_GENL_CMD_TZ_GET_TEMP		3
#endif
#ifndef THERMAL_GENL_CMD_TZ_GET_GOV
#define THERMAL_GENL_CMD_TZ_GET_GOV		4
#endif
#ifndef THERMAL_GENL_CMD_CDEV_GET
#define THERMAL_GENL_CMD_CDEV_GET		6
#endif
#ifndef THERMAL_GENL_CMD_THRESHOLD_GET
#define THERMAL_GENL_CMD_THRESHOLD_GET		7
#endif
