#pragma once
#include <linux/vm_sockets.h>

#ifndef SO_VM_SOCKETS_BUFFER_SIZE
#define SO_VM_SOCKETS_BUFFER_SIZE	0
#endif
#ifndef SO_VM_SOCKETS_BUFFER_MIN_SIZE
#define SO_VM_SOCKETS_BUFFER_MIN_SIZE	1
#endif
#ifndef SO_VM_SOCKETS_BUFFER_MAX_SIZE
#define SO_VM_SOCKETS_BUFFER_MAX_SIZE	2
#endif
#ifndef SO_VM_SOCKETS_PEER_HOST_VM_ID
#define SO_VM_SOCKETS_PEER_HOST_VM_ID	3
#endif
#ifndef SO_VM_SOCKETS_TRUSTED
#define SO_VM_SOCKETS_TRUSTED		5
#endif
#ifndef SO_VM_SOCKETS_CONNECT_TIMEOUT
#define SO_VM_SOCKETS_CONNECT_TIMEOUT	6
#endif
#ifndef SO_VM_SOCKETS_NONBLOCK_TXRX
#define SO_VM_SOCKETS_NONBLOCK_TXRX	7
#endif
