#pragma once
#include <linux/vm_sockets.h>

#ifndef SO_VM_SOCKETS_BUFFER_SIZE
#define SO_VM_SOCKETS_BUFFER_SIZE	0
#endif
#ifndef SO_VM_SOCKETS_BUFFER_MIN_SIZE
#define SO_VM_SOCKETS_BUFFER_MIN_SIZE	1
#endif
#ifndef SO_VM_SOCKETS_BUFFER_MAX_SIZE
#define SO_VM_SOCKETS_BUFFER_MAX_SIZE	2
#endif
#ifndef SO_VM_SOCKETS_PEER_HOST_VM_ID
#define SO_VM_SOCKETS_PEER_HOST_VM_ID	3
#endif
#ifndef SO_VM_SOCKETS_TRUSTED
#define SO_VM_SOCKETS_TRUSTED		5
#endif
#ifndef SO_VM_SOCKETS_CONNECT_TIMEOUT
#define SO_VM_SOCKETS_CONNECT_TIMEOUT	6
#endif
#ifndef SO_VM_SOCKETS_NONBLOCK_TXRX
#define SO_VM_SOCKETS_NONBLOCK_TXRX	7
#endif
#ifndef SO_VM_SOCKETS_CONNECT_TIMEOUT_NEW
#define SO_VM_SOCKETS_CONNECT_TIMEOUT_NEW	9
#endif

#ifndef VMADDR_CID_ANY
#define VMADDR_CID_ANY			((unsigned int)-1)
#endif
#ifndef VMADDR_CID_LOCAL
#define VMADDR_CID_LOCAL		1
#endif
#ifndef VMADDR_PORT_ANY
#define VMADDR_PORT_ANY			((unsigned int)-1)
#endif

#ifndef IOCTL_VM_SOCKETS_GET_LOCAL_CID
#define IOCTL_VM_SOCKETS_GET_LOCAL_CID	_IO(0x07, 0xb9)
#endif
